// ============================================================================
// CRON Feedback-Directed Optimization (FDO) — Profile-Guided Recompilation
// Closes the compile→simulate→profile→recompile loop for the 256-Core
// 4D-Torus VLIW processor. Reads execution profiles generated by cron-vm
// and applies profile-guided transformations to improve VLIW bundle packing.
// ============================================================================

use std::collections::HashMap;
use crate::codegen::{VliwBundle, VliwSlot};
use crate::scheduler::AOTHazardScheduler;

/// Parsed representation of a single bundle's execution profile
#[derive(Debug, Clone, Default)]
pub struct FdoBundleEntry {
    pub cycle: usize,
    pub exec_count: u64,
    pub nop_count: u32,
    pub had_optical_stall: bool,
    pub had_raw_stall: bool,
}

/// Complete parsed FDO execution profile
#[derive(Debug, Clone, Default)]
pub struct FdoProfile {
    pub bundle_entries: Vec<FdoBundleEntry>,
    pub opcode_frequency: HashMap<String, u64>,
    pub total_nops: u64,
    pub avg_slot_utilization: f64,
    pub hottest_bundle_cycle: usize,
    pub underutilized_bundles: u64,
}

/// FDO analysis results and optimization recommendations
#[derive(Debug, Clone, Default)]
pub struct FdoAnalysis {
    /// Cycles of hot bundles (exec_count above threshold)
    pub hot_bundles: Vec<usize>,
    /// Cycles of cold bundles (exec_count == 1 or very low)
    pub cold_bundles: Vec<usize>,
    /// Cycles of bundles with high NOP count (> 2 NOPs = underutilized)
    pub nop_heavy_bundles: Vec<usize>,
    /// Estimated cycle reduction after NOP compaction
    pub estimated_cycle_savings: usize,
    /// Total original cycles
    pub original_cycles: usize,
}

impl FdoAnalysis {
    pub fn summary(&self) -> String {
        format!(
            "[FDO] Hot bundles: {} | Cold bundles: {} | NOP-heavy: {} | Est. savings: {} cycles ({:.1}%)",
            self.hot_bundles.len(),
            self.cold_bundles.len(),
            self.nop_heavy_bundles.len(),
            self.estimated_cycle_savings,
            if self.original_cycles > 0 {
                (self.estimated_cycle_savings as f64 / self.original_cycles as f64) * 100.0
            } else {
                0.0
            }
        )
    }
}

/// Parse a `.prof` text file generated by cron-vm's ExecutionProfile::to_prof_string()
pub fn parse_fdo_profile(prof_text: &str) -> Result<FdoProfile, String> {
    let mut profile = FdoProfile::default();
    let mut section = "";

    for line in prof_text.lines() {
        let trimmed = line.trim();

        // Skip empty lines and comments
        if trimmed.is_empty() || trimmed.starts_with(';') {
            // Parse header metadata from comments
            if trimmed.starts_with("; Total NOPs:") {
                if let Some(val) = trimmed.split(':').nth(1) {
                    profile.total_nops = val.trim().parse().unwrap_or(0);
                }
            } else if trimmed.starts_with("; Avg Slot Utilization:") {
                if let Some(val) = trimmed.split(':').nth(1) {
                    profile.avg_slot_utilization = val.trim().parse().unwrap_or(0.0);
                }
            } else if trimmed.starts_with("; Hottest Bundle:") {
                if let Some(val) = trimmed.split(':').nth(1) {
                    let cycle_str = val.trim().trim_start_matches('B');
                    profile.hottest_bundle_cycle = cycle_str.parse().unwrap_or(0);
                }
            } else if trimmed.starts_with("; Underutilized Bundles:") {
                if let Some(val) = trimmed.split(':').nth(1) {
                    profile.underutilized_bundles = val.trim().parse().unwrap_or(0);
                }
            }
            continue;
        }

        // Section headers
        if trimmed == "[OPCODE_FREQUENCY]" {
            section = "opfreq";
            continue;
        }
        if trimmed == "[BUNDLE_PROFILES]" {
            section = "bundles";
            continue;
        }

        match section {
            "opfreq" => {
                // Format: "  OP = 42"
                if let Some((op, count_str)) = trimmed.split_once('=') {
                    let op_name = op.trim().to_string();
                    let count: u64 = count_str.trim().parse().unwrap_or(0);
                    profile.opcode_frequency.insert(op_name, count);
                }
            }
            "bundles" => {
                // Format: "  B0001: exec=5 nops=2 optical_stall=false raw_stall=false"
                let mut entry = FdoBundleEntry::default();

                // Parse cycle from B<num>:
                if let Some(b_part) = trimmed.split(':').next() {
                    let cycle_str = b_part.trim().trim_start_matches('B');
                    entry.cycle = cycle_str.parse().unwrap_or(0);
                }

                // Parse key=value pairs
                for token in trimmed.split_whitespace() {
                    if let Some((key, val)) = token.split_once('=') {
                        match key {
                            "exec" => entry.exec_count = val.parse().unwrap_or(0),
                            "nops" => entry.nop_count = val.parse().unwrap_or(0),
                            "optical_stall" => entry.had_optical_stall = val == "true",
                            "raw_stall" => entry.had_raw_stall = val == "true",
                            _ => {}
                        }
                    }
                }

                profile.bundle_entries.push(entry);
            }
            _ => {}
        }
    }

    if profile.bundle_entries.is_empty() && profile.opcode_frequency.is_empty() {
        return Err("Empty or invalid FDO profile: no bundle entries or opcode data found".to_string());
    }

    Ok(profile)
}

/// Analyze an FDO profile and produce optimization recommendations
pub fn analyze_profile(profile: &FdoProfile) -> FdoAnalysis {
    let mut analysis = FdoAnalysis {
        original_cycles: profile.bundle_entries.len(),
        ..Default::default()
    };

    // Determine hotness threshold: bundles executed > 5x the minimum non-zero count
    // This handles bimodal distributions (hot loops vs cold setup) correctly
    let mut exec_counts: Vec<u64> = profile
        .bundle_entries
        .iter()
        .map(|b| b.exec_count)
        .filter(|&c| c > 0)
        .collect();
    exec_counts.sort();
    let baseline = if exec_counts.is_empty() {
        1
    } else {
        exec_counts[0].max(1)
    };
    let hot_threshold = baseline * 5;

    for entry in &profile.bundle_entries {
        // Hot bundle detection
        if entry.exec_count >= hot_threshold {
            analysis.hot_bundles.push(entry.cycle);
        }

        // Cold bundle detection
        if entry.exec_count <= 1 {
            analysis.cold_bundles.push(entry.cycle);
        }

        // NOP-heavy detection (more than 2 of 4 slots are NOPs)
        if entry.nop_count > 2 {
            analysis.nop_heavy_bundles.push(entry.cycle);
        }
    }

    // Estimate cycle savings from NOP compaction:
    // Each pair of NOP-heavy bundles (3 NOPs each) could potentially be compacted into 1 bundle
    let compactable_pairs = analysis.nop_heavy_bundles.len() / 2;
    analysis.estimated_cycle_savings = compactable_pairs;

    analysis
}

/// Apply NOP compaction: reschedule bundles with high NOP counts
/// This extracts all non-NOP slots from NOP-heavy bundles and re-packs them
/// using the hazard-aware VLIW scheduler.
pub fn compact_nop_bundles(
    bundles: &[VliwBundle],
    profile: &FdoProfile,
) -> Vec<VliwBundle> {
    let nop_heavy_cycles: std::collections::HashSet<usize> = profile
        .bundle_entries
        .iter()
        .filter(|b| b.nop_count > 2)
        .map(|b| b.cycle)
        .collect();

    if nop_heavy_cycles.is_empty() {
        return bundles.to_vec();
    }

    let mut result = Vec::new();
    let mut pending_slots: Vec<String> = Vec::new();

    for bundle in bundles {
        if nop_heavy_cycles.contains(&bundle.cycle) {
            // Extract non-NOP slots for re-packing
            for slot in &bundle.slots {
                let op = if slot.raw.len() >= 3 {
                    &slot.raw[1..3]
                } else {
                    "NO"
                };
                if op != "NO" {
                    pending_slots.push(slot.raw.clone());
                }
            }
        } else {
            // Flush any pending NOP-compaction slots before emitting a non-NOP-heavy bundle
            if !pending_slots.is_empty() {
                let scheduler = AOTHazardScheduler::new();
                let repacked = scheduler.schedule_raw_slots(
                    &pending_slots,
                    result.len(),
                );
                result.extend(repacked);
                pending_slots.clear();
            }
            result.push(VliwBundle {
                cycle: result.len(),
                slots: [
                    VliwSlot::new(&bundle.slots[0].raw),
                    VliwSlot::new(&bundle.slots[1].raw),
                    VliwSlot::new(&bundle.slots[2].raw),
                    VliwSlot::new(&bundle.slots[3].raw),
                ],
            });
        }
    }

    // Flush remaining pending slots
    if !pending_slots.is_empty() {
        let scheduler = AOTHazardScheduler::new();
        let repacked = scheduler.schedule_raw_slots(&pending_slots, result.len());
        result.extend(repacked);
    }

    // Renumber cycles
    for (i, bundle) in result.iter_mut().enumerate() {
        bundle.cycle = i;
    }

    result
}

/// Apply hot-path inlining hints to machine code bundles.
/// Marks hot bundles with a telemetry annotation for the hardware prefetcher.
pub fn annotate_hot_bundles(
    bundles: &mut [VliwBundle],
    analysis: &FdoAnalysis,
) {
    let hot_set: std::collections::HashSet<usize> = analysis.hot_bundles.iter().copied().collect();

    for bundle in bundles.iter_mut() {
        if hot_set.contains(&bundle.cycle) {
            // For hot bundles, ensure all 4 slots are utilized.
            // If any slot is a NOP, attempt to insert a prefetch hint (PT opcode).
            for slot in &mut bundle.slots {
                let op = if slot.raw.len() >= 3 {
                    &slot.raw[1..3]
                } else {
                    "NO"
                };
                if op == "NO" {
                    // Insert a pipeline prefetch telemetry hint
                    *slot = VliwSlot::new("_PT00#000>");
                    break; // Only one hint per bundle
                }
            }
        }
    }
}

/// Full FDO recompilation pipeline:
/// 1. Parse the profile
/// 2. Analyze for hot/cold/NOP-heavy bundles
/// 3. Compact NOP-heavy bundles
/// 4. Annotate hot bundles with prefetch hints
/// Returns the optimized machine code string and an analysis report.
pub fn fdo_recompile(
    original_cl: &str,
    prof_text: &str,
) -> Result<(String, FdoAnalysis), String> {
    // 1. Parse profile
    let profile = parse_fdo_profile(prof_text)?;

    // 2. Analyze
    let analysis = analyze_profile(&profile);

    // 3. Parse original .cl into bundles
    let mut bundles = parse_cl_to_bundles(original_cl)?;

    // 4. Compact NOP-heavy bundles
    let compacted = compact_nop_bundles(&bundles, &profile);

    // 5. Annotate hot bundles
    bundles = compacted;
    annotate_hot_bundles(&mut bundles, &analysis);

    // 6. Format back to .cl text
    let mut output = String::new();
    for bundle in &bundles {
        output.push_str(&format!(
            "B{:04}: {} {} {} {}\n",
            bundle.cycle,
            bundle.slots[0].raw,
            bundle.slots[1].raw,
            bundle.slots[2].raw,
            bundle.slots[3].raw,
        ));
    }

    Ok((output, analysis))
}

/// Parse .cl text into VliwBundle structs for FDO re-processing
fn parse_cl_to_bundles(cl_code: &str) -> Result<Vec<VliwBundle>, String> {
    let mut bundles = Vec::new();

    for line in cl_code.lines() {
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with(';') || trimmed.starts_with("//") {
            continue;
        }

        let parts: Vec<&str> = trimmed.split_whitespace().collect();
        if parts.len() < 5 {
            continue;
        }

        // Parse cycle from B<num>:
        let cycle_str = parts[0].trim_start_matches('B').trim_end_matches(':');
        let cycle: usize = cycle_str.parse().unwrap_or(bundles.len());

        bundles.push(VliwBundle {
            cycle,
            slots: [
                VliwSlot::new(parts[1]),
                VliwSlot::new(parts[2]),
                VliwSlot::new(parts[3]),
                VliwSlot::new(parts[4]),
            ],
        });
    }

    if bundles.is_empty() {
        return Err("No valid .cl bundles found for FDO processing".to_string());
    }

    Ok(bundles)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_prof() -> String {
        r#"; CRON FDO Execution Profile v1.0
; Generated by cron-vm 4D-Torus Simulator
; Total Bundles: 4
; Total NOPs: 8
; Avg Slot Utilization: 0.5000
; Hottest Bundle: B0002
; Underutilized Bundles: 2

[OPCODE_FREQUENCY]
  PO = 3
  NO = 8
  OP = 1
  HL = 1

[BUNDLE_PROFILES]
  B0000: exec=1 nops=0 optical_stall=false raw_stall=false
  B0001: exec=100 nops=0 optical_stall=false raw_stall=false
  B0002: exec=100 nops=3 optical_stall=false raw_stall=true
  B0003: exec=1 nops=3 optical_stall=false raw_stall=false
"#
        .to_string()
    }

    #[test]
    fn test_parse_fdo_profile() {
        let prof = parse_fdo_profile(&sample_prof()).expect("Parse failed");
        assert_eq!(prof.bundle_entries.len(), 4);
        assert_eq!(prof.total_nops, 8);
        assert!((prof.avg_slot_utilization - 0.5).abs() < 0.01);
        assert_eq!(prof.hottest_bundle_cycle, 2);
        assert_eq!(prof.underutilized_bundles, 2);
        assert_eq!(*prof.opcode_frequency.get("PO").unwrap_or(&0), 3);
    }

    #[test]
    fn test_analyze_profile_hot_cold() {
        let prof = parse_fdo_profile(&sample_prof()).expect("Parse failed");
        let analysis = analyze_profile(&prof);
        assert!(!analysis.hot_bundles.is_empty(), "Should detect hot bundles");
        assert!(!analysis.cold_bundles.is_empty(), "Should detect cold bundles");
        assert!(!analysis.nop_heavy_bundles.is_empty(), "Should detect NOP-heavy bundles");
    }

    #[test]
    fn test_fdo_roundtrip() {
        let cl_code = r#"
        B0000: '=00#000A> '=01#0005> _PO02$100> _SH00$000>
        B0001: _PO03$200> _OP04$100> _NO00#000> _NO00#000>
        B0002: _PO05$300> _NO00#000> _NO00#000> _NO00#000>
        B0003: _NO00#000> _NO00#000> _NO00#000> _HL00$000!
        "#;
        let prof = sample_prof();
        let (optimized, analysis) = fdo_recompile(cl_code, &prof).expect("FDO recompile failed");
        assert!(!optimized.is_empty(), "Optimized output must not be empty");
        assert!(analysis.original_cycles > 0);
    }
}
