// ============================================================================
// CRON FDO (Feedback-Directed Optimization) — Integration Tests
// Tests the compile → simulate → profile → recompile pipeline.
// ============================================================================

use cronc::compile_source;
use cronc::fdo::{parse_fdo_profile, analyze_profile, fdo_recompile};

fn sample_cr_program() -> &'static str {
    r#"
    .MODULE FDOTest
    .ENTRY _main

    def compute(a: u32, b: u32) -> u32 {
        let sum = a + b
        let product = a * b
        return sum + product
    }

    _main:
        let x = compute(10, 20)
        let y = compute(x, 5)
        export y as result_y
    .END
    "#
}

fn sample_fdo_profile() -> String {
    r#"; CRON FDO Execution Profile v1.0
; Generated by cron-vm 4D-Torus Simulator
; Total Bundles: 6
; Total NOPs: 12
; Avg Slot Utilization: 0.5000
; Hottest Bundle: B0003
; Underutilized Bundles: 3

[OPCODE_FREQUENCY]
  PO = 8
  NO = 12
  OP = 2
  HL = 1
  FA = 1
  GU = 2

[BUNDLE_PROFILES]
  B0000: exec=1 nops=0 optical_stall=false raw_stall=false
  B0001: exec=1 nops=0 optical_stall=false raw_stall=false
  B0002: exec=50 nops=1 optical_stall=false raw_stall=false
  B0003: exec=200 nops=0 optical_stall=true raw_stall=true
  B0004: exec=1 nops=3 optical_stall=false raw_stall=false
  B0005: exec=1 nops=3 optical_stall=false raw_stall=false
"#
    .to_string()
}

// ============================================================================
// Profile Parsing Tests
// ============================================================================

#[test]
fn test_fdo_parse_profile_metadata() {
    let prof = parse_fdo_profile(&sample_fdo_profile()).expect("Parse failed");
    assert_eq!(prof.total_nops, 12);
    assert!((prof.avg_slot_utilization - 0.5).abs() < 0.01);
    assert_eq!(prof.hottest_bundle_cycle, 3);
    assert_eq!(prof.underutilized_bundles, 3);
}

#[test]
fn test_fdo_parse_profile_opcode_frequencies() {
    let prof = parse_fdo_profile(&sample_fdo_profile()).expect("Parse failed");
    assert_eq!(*prof.opcode_frequency.get("PO").unwrap_or(&0), 8);
    assert_eq!(*prof.opcode_frequency.get("NO").unwrap_or(&0), 12);
    assert_eq!(*prof.opcode_frequency.get("OP").unwrap_or(&0), 2);
    assert_eq!(*prof.opcode_frequency.get("GU").unwrap_or(&0), 2);
}

#[test]
fn test_fdo_parse_profile_bundle_entries() {
    let prof = parse_fdo_profile(&sample_fdo_profile()).expect("Parse failed");
    assert_eq!(prof.bundle_entries.len(), 6);
    assert_eq!(prof.bundle_entries[3].exec_count, 200);
    assert!(prof.bundle_entries[3].had_optical_stall);
    assert!(prof.bundle_entries[3].had_raw_stall);
    assert_eq!(prof.bundle_entries[4].nop_count, 3);
}

#[test]
fn test_fdo_parse_empty_profile_rejected() {
    let result = parse_fdo_profile("");
    assert!(result.is_err(), "Empty profile should be rejected");
}

// ============================================================================
// Profile Analysis Tests
// ============================================================================

#[test]
fn test_fdo_analyze_detects_hot_bundles() {
    let prof = parse_fdo_profile(&sample_fdo_profile()).expect("Parse failed");
    let analysis = analyze_profile(&prof);
    assert!(
        !analysis.hot_bundles.is_empty(),
        "Should detect hot bundles (exec=200 and exec=50)"
    );
    // B0003 (exec=200) should definitely be hot
    assert!(
        analysis.hot_bundles.contains(&3),
        "B0003 with exec=200 should be hot"
    );
}

#[test]
fn test_fdo_analyze_detects_cold_bundles() {
    let prof = parse_fdo_profile(&sample_fdo_profile()).expect("Parse failed");
    let analysis = analyze_profile(&prof);
    assert!(
        !analysis.cold_bundles.is_empty(),
        "Should detect cold bundles (exec=1)"
    );
}

#[test]
fn test_fdo_analyze_detects_nop_heavy_bundles() {
    let prof = parse_fdo_profile(&sample_fdo_profile()).expect("Parse failed");
    let analysis = analyze_profile(&prof);
    assert!(
        !analysis.nop_heavy_bundles.is_empty(),
        "Should detect NOP-heavy bundles (nops=3)"
    );
    // B0004 and B0005 both have 3 NOPs
    assert!(analysis.nop_heavy_bundles.contains(&4));
    assert!(analysis.nop_heavy_bundles.contains(&5));
}

#[test]
fn test_fdo_analysis_cycle_savings_estimation() {
    let prof = parse_fdo_profile(&sample_fdo_profile()).expect("Parse failed");
    let analysis = analyze_profile(&prof);
    assert_eq!(analysis.original_cycles, 6);
    // 2 NOP-heavy bundles can potentially compact into 1
    assert!(
        analysis.estimated_cycle_savings > 0,
        "Should estimate cycle savings from NOP compaction"
    );
}

// ============================================================================
// FDO Recompilation Round-Trip Tests
// ============================================================================

#[test]
fn test_fdo_full_roundtrip_compile_and_recompile() {
    // 1. Compile source to .cl
    let cl_code = compile_source(sample_cr_program())
        .expect("Initial compilation failed");
    assert!(!cl_code.is_empty(), "CL output must not be empty");

    // 2. Recompile with FDO profile
    let prof = sample_fdo_profile();
    let (optimized, analysis) = fdo_recompile(&cl_code, &prof)
        .expect("FDO recompilation failed");

    // 3. Verify optimized output is valid
    assert!(!optimized.is_empty(), "Optimized CL must not be empty");
    assert!(
        optimized.contains("B0000:"),
        "Must contain at least one bundle"
    );

    // 4. Verify analysis report
    assert!(analysis.original_cycles > 0, "Must report original cycle count");
}

#[test]
fn test_fdo_recompile_reduces_nop_count() {
    // Generate a CL program with intentionally NOP-heavy bundles
    let nop_heavy_cl = r#"
    B0000: '=00#000A> '=01#0005> _PO02$100> _SH00$000>
    B0001: _PO03$200> _NO00#000> _NO00#000> _NO00#000>
    B0002: _PO04$300> _NO00#000> _NO00#000> _NO00#000>
    B0003: _GU05$200> _NO00#000> _NO00#000> _HL00$000!
    "#;

    let prof = r#"; CRON FDO Execution Profile v1.0
; Total Bundles: 4
; Total NOPs: 9
; Avg Slot Utilization: 0.4375
; Hottest Bundle: B0000
; Underutilized Bundles: 3

[OPCODE_FREQUENCY]
  PO = 3
  NO = 9
  GU = 1
  HL = 1
  SH = 1

[BUNDLE_PROFILES]
  B0000: exec=1 nops=0 optical_stall=false raw_stall=false
  B0001: exec=10 nops=3 optical_stall=false raw_stall=false
  B0002: exec=10 nops=3 optical_stall=false raw_stall=false
  B0003: exec=1 nops=3 optical_stall=false raw_stall=false
"#;

    let (optimized, _analysis) = fdo_recompile(nop_heavy_cl, prof)
        .expect("FDO recompilation failed");

    assert!(!optimized.is_empty(), "Optimized output must not be empty");

    // Count bundles in optimized output
    let optimized_bundles = optimized.lines()
        .filter(|l| l.trim().starts_with('B'))
        .count();

    // The optimized version should have fewer or equal bundles
    assert!(
        optimized_bundles <= 4,
        "FDO should not increase bundle count (got {} from 4)",
        optimized_bundles
    );
}

#[test]
fn test_fdo_analysis_summary_format() {
    let prof = parse_fdo_profile(&sample_fdo_profile()).expect("Parse failed");
    let analysis = analyze_profile(&prof);
    let summary = analysis.summary();
    assert!(summary.contains("[FDO]"), "Summary must have FDO prefix");
    assert!(summary.contains("Hot bundles"), "Summary must report hot bundles");
    assert!(summary.contains("Cold bundles"), "Summary must report cold bundles");
    assert!(summary.contains("NOP-heavy"), "Summary must report NOP-heavy bundles");
}

#[test]
fn test_fdo_compile_source_with_fdo_api() {
    let prof = sample_fdo_profile();
    let result = cronc::compile_source_with_fdo(sample_cr_program(), &prof);
    assert!(result.is_ok(), "compile_source_with_fdo should succeed: {:?}", result.err());
    let optimized = result.unwrap();
    assert!(!optimized.is_empty(), "FDO-optimized output must not be empty");
}
