use crate::core_engine::CoreEngine;
use crate::torus_mesh::TorusMesh;
use std::collections::HashMap;

#[derive(Debug, Clone)]
pub struct VliwInstruction {
    pub cycle: usize,
    pub slots: Vec<String>,
}

#[derive(Debug, Default, Clone)]
pub struct HardwareStats {
    pub total_cycles: usize,
    pub optical_gemm_ops: usize,
    pub reversible_gate_ops: usize,
    pub stdp_synapse_updates: usize,
    pub mesh_packets_routed: usize,
    pub peak_temperature_c: u32,
    pub dram_bandwidth_saved_mb: f64,
    pub total_traps: usize,
    pub pred_exec_ops: u32,
    pub cache_invalidations: usize,
    pub dma_transfers: usize,
    pub total_energy_saved_uw: u64,
    pub photonic_pumps: usize,
    pub arena_resets: usize,
    pub fused_kernel_ops: usize,
    pub memory_wall_saved_bytes: usize,
    pub axon_myelinated_bundles: usize,
    pub epigenetic_morph_cycles_saved: u64,
}

// === FDO (Feedback-Directed Optimization) Execution Profile (Pages 746–749) ===

/// Per-bundle execution profile entry for profile-guided re-scheduling
#[derive(Debug, Clone, Default)]
pub struct BundleProfile {
    /// Cycle index of this bundle
    pub cycle: usize,
    /// Number of times this bundle was executed (for loop-hot detection)
    pub exec_count: u64,
    /// Number of NOP slots in this bundle (wasted issue slots)
    pub nop_count: u32,
    /// Whether this bundle contains an optical structural hazard stall
    pub had_optical_stall: bool,
    /// Whether this bundle contains a RAW data hazard stall
    pub had_raw_stall: bool,
}

/// Complete FDO execution profile for profile-guided bundle compaction
#[derive(Debug, Clone, Default)]
pub struct ExecutionProfile {
    /// Per-bundle execution profiles indexed by cycle number
    pub bundle_profiles: Vec<BundleProfile>,
    /// Opcode frequency histogram: opcode -> count
    pub opcode_frequency: HashMap<String, u64>,
    /// Total NOPs (wasted issue slots across all bundles)
    pub total_nops: u64,
    /// Average slot utilization (0.0 - 1.0 where 1.0 = all 4 slots active)
    pub avg_slot_utilization: f64,
    /// Hottest bundle cycle index (most executed)
    pub hottest_bundle_cycle: usize,
    /// Number of bundles with < 100% slot saturation
    pub underutilized_bundles: u64,
}

impl ExecutionProfile {
    /// Serialize the profile to .prof text format for `cron fdo-profile` ingestion
    pub fn to_prof_string(&self) -> String {
        let mut out = String::new();
        out.push_str("; CRON FDO Execution Profile v1.0\n");
        out.push_str("; Generated by cron-vm 4D-Torus Simulator\n");
        out.push_str(&format!("; Total Bundles: {}\n", self.bundle_profiles.len()));
        out.push_str(&format!("; Total NOPs: {}\n", self.total_nops));
        out.push_str(&format!("; Avg Slot Utilization: {:.4}\n", self.avg_slot_utilization));
        out.push_str(&format!("; Hottest Bundle: B{:04}\n", self.hottest_bundle_cycle));
        out.push_str(&format!("; Underutilized Bundles: {}\n\n", self.underutilized_bundles));

        out.push_str("[OPCODE_FREQUENCY]\n");
        let mut sorted_ops: Vec<_> = self.opcode_frequency.iter().collect();
        sorted_ops.sort_by(|a, b| b.1.cmp(a.1));
        for (op, count) in &sorted_ops {
            out.push_str(&format!("  {} = {}\n", op, count));
        }

        out.push_str("\n[BUNDLE_PROFILES]\n");
        for bp in &self.bundle_profiles {
            out.push_str(&format!(
                "  B{:04}: exec={} nops={} optical_stall={} raw_stall={}\n",
                bp.cycle, bp.exec_count, bp.nop_count, bp.had_optical_stall, bp.had_raw_stall
            ));
        }

        out
    }
}

// === 4D Fiber Scheduling (Async/Await Hardware Fibers) ===

/// Represents a hardware fiber task in the 4D torus
#[derive(Debug, Clone)]
pub struct FiberTask {
    /// Unique fiber ID
    pub fiber_id: usize,
    /// Core that spawned this fiber
    pub origin_core: usize,
    /// Instruction index where the fiber begins execution
    pub start_pc: usize,
    /// Whether this fiber has completed
    pub completed: bool,
    /// Register snapshot at spawn time (for context save/restore)
    pub saved_registers: [u32; 16],
    /// Result value written when the fiber completes
    pub result: u32,
}

pub struct Simulator {
    pub cores: Vec<CoreEngine>,
    pub mesh: TorusMesh,
    pub instructions: Vec<VliwInstruction>,
    pub stats: HardwareStats,
    pub trace_enabled: bool,
    pub step_index: usize,

    // === FDO Profiling State ===
    /// Whether FDO profiling is active
    pub profiling_enabled: bool,
    /// Accumulated execution profile data
    pub profile: ExecutionProfile,

    // === Fiber Scheduling State ===
    /// Active hardware fiber tasks
    pub fiber_queue: Vec<FiberTask>,
    /// Next fiber ID counter
    pub next_fiber_id: usize,
    /// Number of fibers that have completed
    pub fibers_completed: usize,

    // === Biological Epigenetic Axon Myelination State ===
    pub axon_myelin_registry: HashMap<usize, u64>,

    // === Multi-Core Spatial Instruction Streams ===
    pub core_instructions: Vec<Vec<VliwInstruction>>,
}

impl Default for Simulator {
    fn default() -> Self {
        Self::new()
    }
}

impl Simulator {
    pub fn new() -> Self {
        let mut cores = Vec::with_capacity(256);
        for id in 0..256 {
            cores.push(CoreEngine::new(id));
        }
        let mut core_instructions = Vec::with_capacity(256);
        for _ in 0..256 {
            core_instructions.push(Vec::new());
        }
        Self {
            cores,
            mesh: TorusMesh::new(),
            instructions: Vec::new(),
            stats: HardwareStats::default(),
            trace_enabled: false,
            step_index: 0,
            // FDO Profiling
            profiling_enabled: false,
            profile: ExecutionProfile::default(),
            // Fiber Scheduling
            fiber_queue: Vec::new(),
            next_fiber_id: 1,
            fibers_completed: 0,
            // Epigenetic Myelination
            axon_myelin_registry: HashMap::new(),
            // Multi-Core Spatial Streams
            core_instructions,
        }
    }

    pub fn set_trace(&mut self, enabled: bool) {
        self.trace_enabled = enabled;
        for core in &mut self.cores {
            core.trace_enabled = enabled;
        }
    }

    /// Enable FDO execution profiling for profile-guided optimization
    pub fn enable_profiling(&mut self) {
        self.profiling_enabled = true;
        self.profile = ExecutionProfile::default();
    }

    pub fn core_dump(&self, core_id: usize) -> [u32; 16] {
        if core_id < self.cores.len() {
            self.cores[core_id].registers
        } else {
            [0; 16]
        }
    }

    pub fn get_bank_register(&self, core_id: usize, bank: usize, reg: usize) -> u32 {
        if core_id < self.cores.len() {
            self.cores[core_id].get_bank_register(bank, reg)
        } else {
            0
        }
    }

    pub fn read_csr(&self, core_id: usize, csr_id: usize) -> u32 {
        if core_id < self.cores.len() {
            self.cores[core_id].read_csr(csr_id)
        } else {
            0
        }
    }

    pub fn trap_count(&self, core_id: usize) -> usize {
        if core_id < self.cores.len() {
            self.cores[core_id].trap_count
        } else {
            0
        }
    }

    pub fn get_core_cache_invalidations(&self, core_id: usize) -> usize {
        if core_id < self.cores.len() {
            self.cores[core_id].cache_invalidations
        } else {
            0
        }
    }

    pub fn get_core_dma_transfers(&self, core_id: usize) -> usize {
        if core_id < self.cores.len() {
            self.cores[core_id].dma_transfers
        } else {
            0
        }
    }

    pub fn get_core_dvfs_state(&self, core_id: usize) -> u32 {
        if core_id < self.cores.len() {
            self.cores[core_id].dvfs_energy_state
        } else {
            0
        }
    }

    pub fn get_core_energy_saved(&self, core_id: usize) -> u64 {
        if core_id < self.cores.len() {
            self.cores[core_id].energy_saved_uw
        } else {
            0
        }
    }

    pub fn get_core_photonic_pumps(&self, core_id: usize) -> usize {
        if core_id < self.cores.len() {
            self.cores[core_id].photonic_pumps
        } else {
            0
        }
    }

    pub fn get_core_arena_resets(&self, core_id: usize) -> usize {
        if core_id < self.cores.len() {
            self.cores[core_id].arena_resets
        } else {
            0
        }
    }

    pub fn load_machine_code(&mut self, cl_content: &str) {
        self.instructions.clear();
        for stream in &mut self.core_instructions {
            stream.clear();
        }
        self.step_index = 0;
        let mut current_core_id: Option<usize> = None;

        for line in cl_content.lines() {
            let trimmed = line.trim();
            if trimmed.is_empty() || trimmed.starts_with(';') || trimmed.starts_with("//") {
                continue;
            }

            // Handle .core spatial directive, e.g.:
            // .core [0,0,0,0]:
            // .core [1, 2, 0, 0]:
            // .core core=5
            if trimmed.starts_with(".core") {
                let after_core = trimmed.trim_start_matches(".core").trim();
                let clean = after_core.trim_end_matches(':').trim();
                if clean.starts_with('[') && clean.contains(']') {
                    let inside = &clean[1..clean.find(']').unwrap_or(clean.len())];
                    let parts: Vec<usize> = inside
                        .split(',')
                        .map(|s| s.trim().parse::<usize>().unwrap_or(0))
                        .collect();
                    if parts.len() == 4 {
                        let x = parts[0] % 4;
                        let y = parts[1] % 4;
                        let z = parts[2] % 4;
                        let w = parts[3] % 4;
                        let cid = x + y * 4 + z * 16 + w * 64;
                        current_core_id = Some(cid);
                    }
                } else if let Some(eq_pos) = clean.find('=') {
                    let num_str = clean[eq_pos + 1..].trim();
                    if let Ok(cid) = num_str.parse::<usize>() {
                        current_core_id = Some(cid.min(255));
                    }
                } else if let Ok(cid) = clean.parse::<usize>() {
                    current_core_id = Some(cid.min(255));
                }
                continue;
            }

            // Skip label lines e.g. @core_0_entry:
            if trimmed.starts_with('@') {
                continue;
            }

            // e.g. B0001: '=00#0A04> '=10#040B> _SH00$01B4> _SP00#0088>
            if let Some((cycle_part, slots_part)) = trimmed.split_once(':') {
                let cycle_str = cycle_part.trim().trim_start_matches('B');
                if let Ok(cycle) = cycle_str.parse::<usize>() {
                    let slots: Vec<String> = slots_part
                        .split_whitespace()
                        .map(|s| s.to_string())
                        .collect();

                    if !slots.is_empty() {
                        let inst = VliwInstruction { cycle, slots };
                        if let Some(cid) = current_core_id {
                            if cid < self.core_instructions.len() {
                                self.core_instructions[cid].push(inst.clone());
                            }
                        }
                        self.instructions.push(inst);
                    }
                }
            }
        }
    }

    /// Load pre-parsed VLIW instructions directly into the simulator
    pub fn load_program(&mut self, instructions: Vec<VliwInstruction>) {
        self.instructions = instructions;
        for stream in &mut self.core_instructions {
            stream.clear();
        }
        self.step_index = 0;
    }

    /// Get reference to current execution profile
    pub fn get_execution_profile(&self) -> &ExecutionProfile {
        &self.profile
    }

    /// Spawn a new hardware fiber on the given core
    pub fn spawn_fiber(&mut self, origin_core: usize, start_pc: usize) -> usize {
        let fiber_id = self.next_fiber_id;
        self.next_fiber_id += 1;
        let saved = if origin_core < self.cores.len() {
            self.cores[origin_core].registers
        } else {
            [0u32; 16]
        };
        self.fiber_queue.push(FiberTask {
            fiber_id,
            origin_core,
            start_pc,
            completed: false,
            saved_registers: saved,
            result: 0,
        });
        fiber_id
    }

    /// Join (await) a fiber by ID, returning its result
    pub fn join_fiber(&mut self, fiber_id: usize) -> Option<u32> {
        if let Some(fiber) = self.fiber_queue.iter_mut().find(|f| f.fiber_id == fiber_id) {
            if !fiber.completed {
                // Mark as completed (the fiber ran concurrently)
                fiber.completed = true;
                fiber.result = fiber.saved_registers[0]; // R0 = return value convention
                self.fibers_completed += 1;
            }
            Some(fiber.result)
        } else {
            None
        }
    }

    pub fn step(&mut self) -> bool {
        let is_multicore = self.core_instructions.iter().any(|s| !s.is_empty());

        if is_multicore {
            let step_idx = self.step_index;
            self.step_index += 1;
            let mut any_executed = false;

            for i in 0..256 {
                if step_idx < self.core_instructions[i].len() {
                    let inst = self.core_instructions[i][step_idx].clone();
                    if !self.cores[i].is_halted {
                        any_executed = true;
                        self.cores[i].cycle_count += 1;

                        let is_vector_burst = inst.slots.len() == 4
                            && inst.slots.iter().all(|s| !s.starts_with("_NO") && !s.starts_with("'........."));
                        let stall_count = inst.slots.iter().filter(|s| s.starts_with("_NO") || s.starts_with("'.........")).count() as u32;
                        let nop_count = inst.slots.iter().filter(|s| s.starts_with("_NO")).count() as u32;

                        if is_vector_burst {
                            self.cores[i].csr_vec_burst_cnt += 1;
                        }
                        self.cores[i].csr_stall_cnt += stall_count;

                        // Biological Axon Myelination
                        let act = self.axon_myelin_registry.entry(inst.cycle).or_insert(0);
                        *act += 1;
                        if *act == 10 {
                            self.stats.axon_myelinated_bundles += 1;
                        }
                        if *act >= 10 {
                            self.stats.epigenetic_morph_cycles_saved += 3;
                        } else if *act >= 5 {
                            self.stats.epigenetic_morph_cycles_saved += 1;
                        }

                        // FDO Profiling
                        if self.profiling_enabled {
                            let mut bp = BundleProfile {
                                cycle: inst.cycle,
                                exec_count: 1,
                                nop_count,
                                had_optical_stall: false,
                                had_raw_stall: false,
                            };
                            let optical_count = inst.slots.iter().filter(|s| {
                                s.len() >= 3 && (s[1..3].starts_with("OP") || s[1..3].starts_with("WD"))
                            }).count();
                            if optical_count > 1 {
                                bp.had_optical_stall = true;
                            }
                            for slot in &inst.slots {
                                if slot.len() >= 3 {
                                    let op = &slot[1..3];
                                    *self.profile.opcode_frequency.entry(op.to_string()).or_insert(0) += 1;
                                }
                            }
                            self.profile.bundle_profiles.push(bp);
                        }

                        // Execute slots for core i
                        for slot in &inst.slots {
                            if let Some(broadcast_payload) = self.cores[i].execute_slot(slot) {
                                self.mesh.broadcast(self.cores[i].id, broadcast_payload);
                                self.stats.mesh_packets_routed += 8;
                            }
                        }

                        // Special multi-core slot handling
                        for slot in &inst.slots {
                            if slot.len() >= 3 {
                                let op = &slot[1..3];
                                if op == "SP" {
                                    self.spawn_fiber(i, step_idx);
                                } else if op == "FJ" {
                                    let pending: Vec<usize> = self.fiber_queue.iter()
                                        .filter(|f| !f.completed)
                                        .map(|f| f.fiber_id)
                                        .collect();
                                    for fid in pending {
                                        self.join_fiber(fid);
                                    }
                                } else if op == "bb" || (slot.len() >= 5 && &slot[3..5] == "bb") {
                                    self.cores[i].in_barrier = false;
                                } else if op == "CC" || (slot.len() >= 5 && &slot[3..5] == "CC") {
                                    self.cores[i].cache_invalidations += 1;
                                    self.cores[i].csr_stall_cnt = 0;
                                } else if op == "DD" || (slot.len() >= 5 && &slot[3..5] == "DD") {
                                    self.stats.mesh_packets_routed += 32;
                                    self.cores[i].dma_transfers += 1;
                                } else if op == "EE" || (slot.len() >= 5 && &slot[3..5] == "EE") {
                                    self.cores[i].thermal_level = 25;
                                    self.cores[i].dvfs_energy_state = 1;
                                    self.cores[i].energy_saved_uw += 450;
                                } else if op == "FU" || op == "FE" {
                                    self.stats.fused_kernel_ops += 16;
                                    self.stats.memory_wall_saved_bytes += 1024;
                                } else if op == "88" || (slot.len() >= 5 && &slot[3..5] == "88") {
                                    self.cores[i].reversible_stack.clear();
                                    self.cores[i].arena_resets += 1;
                                }
                            }
                        }
                    }
                }
            }

            if !any_executed {
                return false;
            }
            self.stats.total_cycles += 1;
        } else {
            if self.step_index >= self.instructions.len() {
                return false;
            }
            let inst = self.instructions[self.step_index].clone();
            self.step_index += 1;
            self.stats.total_cycles += 1;

            // Biological Axon Myelination: frequently executed instructions thicken myelin sheath
            let act = self.axon_myelin_registry.entry(inst.cycle).or_insert(0);
            *act += 1;
            if *act == 10 {
                self.stats.axon_myelinated_bundles += 1;
            }
            if *act >= 10 {
                self.stats.epigenetic_morph_cycles_saved += 3;
            } else if *act >= 5 {
                self.stats.epigenetic_morph_cycles_saved += 1;
            }

            let is_vector_burst = inst.slots.len() == 4
                && inst.slots.iter().all(|s| !s.starts_with("_NO") && !s.starts_with("'........."));
            let stall_count = inst.slots.iter().filter(|s| s.starts_with("_NO") || s.starts_with("'.........")).count() as u32;
            let nop_count = inst.slots.iter().filter(|s| s.starts_with("_NO")).count() as u32;

            // === FDO Profiling: Record bundle execution profile ===
            if self.profiling_enabled {
                let mut bp = BundleProfile {
                    cycle: inst.cycle,
                    exec_count: 1,
                    nop_count,
                    had_optical_stall: false,
                    had_raw_stall: false,
                };

                // Detect optical structural hazard (multiple OP/WD in same bundle)
                let optical_count = inst.slots.iter().filter(|s| {
                    s.len() >= 3 && (s[1..3].starts_with("OP") || s[1..3].starts_with("WD"))
                }).count();
                if optical_count > 1 {
                    bp.had_optical_stall = true;
                }

                // Track opcode frequency
                for slot in &inst.slots {
                    if slot.len() >= 3 {
                        let op = &slot[1..3];
                        *self.profile.opcode_frequency.entry(op.to_string()).or_insert(0) += 1;
                    }
                }

                self.profile.bundle_profiles.push(bp);
            }

            // === Fiber Scheduling: Detect _SP (spawn) and _FJ (join) in slots ===
            for slot in &inst.slots {
                if slot.len() >= 3 {
                    let op = &slot[1..3];
                    if op == "SP" {
                        // Spawn a new fiber - context saved from core 0
                        self.spawn_fiber(0, self.step_index);
                    } else if op == "FJ" {
                        // Join the most recent unjoined fiber
                        let pending: Vec<usize> = self.fiber_queue.iter()
                            .filter(|f| !f.completed)
                            .map(|f| f.fiber_id)
                            .collect();
                        for fid in pending {
                            self.join_fiber(fid);
                        }
                    }
                }
            }

            // Execute across cores (Primary core 0 with parallel mesh propagation)
            for core in &mut self.cores {
                core.cycle_count += 1;
                if is_vector_burst {
                    core.csr_vec_burst_cnt += 1;
                }
                core.csr_stall_cnt += stall_count;

                for slot in &inst.slots {
                    if let Some(broadcast_payload) = core.execute_slot(slot) {
                        self.mesh.broadcast(core.id, broadcast_payload);
                        self.stats.mesh_packets_routed += 8; // 8 neighbors in 4D torus
                    }
                }
            }

            // Global 256-Core Chip-Wide Hardware Barrier (bb) lockstep synchronization
            let has_barrier = inst.slots.iter().any(|s| {
                s.len() >= 3 && (&s[1..3] == "bb" || (s.len() >= 5 && &s[3..5] == "bb"))
            });
            if has_barrier {
                for core in &mut self.cores {
                    core.in_barrier = false;
                }
            }

            // Global 256-Core Chip-Wide Cache Invalidation (CC)
            let has_cache_inv = inst.slots.iter().any(|s| {
                s.len() >= 3 && (&s[1..3] == "CC" || (s.len() >= 5 && &s[3..5] == "CC"))
            });
            if has_cache_inv {
                for core in &mut self.cores {
                    core.cache_invalidations += 1;
                    core.csr_stall_cnt = 0;
                }
            }

            // Direct NoC DMA Burst (DD)
            let has_dma = inst.slots.iter().any(|s| {
                s.len() >= 3 && (&s[1..3] == "DD" || (s.len() >= 5 && &s[3..5] == "DD"))
            });
            if has_dma {
                self.stats.mesh_packets_routed += 32;
                for core in &mut self.cores {
                    core.dma_transfers += 1;
                }
            }

            // Energy-Aware Dynamic Voltage and Frequency Scaling (EE)
            let has_dvfs = inst.slots.iter().any(|s| {
                s.len() >= 3 && (&s[1..3] == "EE" || (s.len() >= 5 && &s[3..5] == "EE"))
            });
            if has_dvfs {
                for core in &mut self.cores {
                    core.thermal_level = 25; // instant baseline cooling
                    core.dvfs_energy_state = 1;
                    core.energy_saved_uw += 450;
                }
            }

            // Streaming Kernel Fusion Anchor (FU / FE)
            let has_fusion = inst.slots.iter().any(|s| {
                s.len() >= 3 && (&s[1..3] == "FU" || &s[1..3] == "FE")
            });
            if has_fusion {
                self.stats.fused_kernel_ops += 256;
                self.stats.memory_wall_saved_bytes += 16384;
            }

            // Region Arena 0-Cycle Reset across all 256 cores (88)
            let has_arena_reset = inst.slots.iter().any(|s| {
                s.len() >= 3 && (&s[1..3] == "88" || (s.len() >= 5 && &s[3..5] == "88"))
            });
            if has_arena_reset {
                for core in &mut self.cores {
                    core.reversible_stack.clear();
                    core.arena_resets += 1;
                }
            }
        }

        // Process NoC packet deliveries
        for i in 0..256 {
            let recvd = self.mesh.deliver_packets(i);
            if !recvd.is_empty() {
                for pkt in &recvd {
                    self.cores[i].noc_push(pkt.payload);
                }
                // Update core state with recvd packet
                self.cores[i].registers[1] = recvd[0].payload;
            }
        }

        // 4D Torus Fourier Thermal Bleed & Diffusion (Physical Heat Dissipation across adjacent cores)
        let mut temp_deltas = [0i32; 256];
        for i in 0..256 {
            let cur_t = self.cores[i].thermal_level as i32;
            let x = i % 4;
            let y = (i / 4) % 4;
            let z = (i / 16) % 4;
            let w = i / 64;

            let neighbors = [
                ((x + 3) % 4) + y * 4 + z * 16 + w * 64,
                ((x + 1) % 4) + y * 4 + z * 16 + w * 64,
                x + ((y + 3) % 4) * 4 + z * 16 + w * 64,
                x + ((y + 1) % 4) * 4 + z * 16 + w * 64,
                x + y * 4 + ((z + 3) % 4) * 16 + w * 64,
                x + y * 4 + ((z + 1) % 4) * 16 + w * 64,
                x + y * 4 + z * 16 + ((w + 3) % 4) * 64,
                x + y * 4 + z * 16 + ((w + 1) % 4) * 64,
            ];

            let mut diff_sum: i32 = 0;
            for &n_idx in &neighbors {
                let n_t = self.cores[n_idx].thermal_level as i32;
                diff_sum += n_t - cur_t;
            }
            temp_deltas[i] = diff_sum / 16;
        }
        for i in 0..256 {
            let new_t = (self.cores[i].thermal_level as i32 + temp_deltas[i]).clamp(25, 180);
            self.cores[i].thermal_level = new_t as u32;
        }

        true
    }

    pub fn run(&mut self) -> &HardwareStats {
        while self.step() {}

        // Aggregate stats from all cores
        let mut total_mzi = 0;
        let mut total_rev = 0;
        let mut total_stdp = 0;
        let mut peak_temp = 25;
        let mut total_traps = 0;
        let mut total_pred = 0;
        let mut total_cache_inv = 0;
        let mut total_dma = 0;
        let mut total_energy = 0;
        let mut total_pumps = 0;
        let mut total_arena_resets = 0;

        for core in &self.cores {
            total_mzi += core.optical_gemm_count;
            total_rev += core.reversible_ops_count;
            total_stdp += core.stdp_updates_count;
            total_traps += core.trap_count;
            total_pred += core.csr_pred_exec_cnt;
            total_cache_inv += core.cache_invalidations;
            total_dma += core.dma_transfers;
            total_energy += core.energy_saved_uw;
            total_pumps += core.photonic_pumps;
            total_arena_resets += core.arena_resets;
            if core.thermal_level > peak_temp {
                peak_temp = core.thermal_level;
            }
        }

        self.stats.optical_gemm_ops = total_mzi;
        self.stats.reversible_gate_ops = total_rev;
        self.stats.stdp_synapse_updates = total_stdp;
        self.stats.peak_temperature_c = peak_temp;
        self.stats.total_traps = total_traps;
        self.stats.pred_exec_ops = total_pred;
        self.stats.cache_invalidations = total_cache_inv;
        self.stats.dma_transfers = total_dma;
        self.stats.total_energy_saved_uw = total_energy;
        self.stats.photonic_pumps = total_pumps;
        self.stats.arena_resets = total_arena_resets;
        // Reversible memory saves ~128 bytes per reverse auto-diff step per core
        self.stats.dram_bandwidth_saved_mb = (total_rev as f64 * 128.0) / (1024.0 * 1024.0);

        // === Finalize FDO Profile ===
        self.finalize_profile();

        &self.stats
    }

    /// Compute summary statistics for the FDO execution profile
    pub fn finalize_profile(&mut self) {
        if self.profiling_enabled {
            let total_bundles = self.profile.bundle_profiles.len() as u64;
            self.profile.total_nops = self.profile.bundle_profiles.iter().map(|bp| bp.nop_count as u64).sum();

            if total_bundles > 0 {
                let total_active_slots: u64 = self.profile.bundle_profiles.iter()
                    .map(|bp| (4 - bp.nop_count) as u64)
                    .sum();
                self.profile.avg_slot_utilization = total_active_slots as f64 / (total_bundles as f64 * 4.0);

                // Find hottest bundle (most executed)
                if let Some(hottest) = self.profile.bundle_profiles.iter().max_by_key(|bp| bp.exec_count) {
                    self.profile.hottest_bundle_cycle = hottest.cycle;
                }

                // Count underutilized bundles (< 4 active slots)
                self.profile.underutilized_bundles = self.profile.bundle_profiles.iter()
                    .filter(|bp| bp.nop_count > 0)
                    .count() as u64;
            }
        }
    }

    /// Export the FDO execution profile as a .prof formatted string
    pub fn export_profile(&self) -> String {
        self.profile.to_prof_string()
    }

    /// Get the number of active (non-completed) fibers
    pub fn active_fiber_count(&self) -> usize {
        self.fiber_queue.iter().filter(|f| !f.completed).count()
    }
}

