[package]
name = "cron-rt"
version = "0.1.0"
edition = "2021"
description = "CRON Native Runtime & C-ABI Shared Library (cron_rt.dll / libcron_rt.so)"

[lib]
name = "cron_rt"
crate-type = ["cdylib", "rlib", "staticlib"]

[dependencies]
cronc = { path = "../cronc" }
cron-vm = { path = "../cron-vm" }
libc = "0.2"
