"""
CRON Programming Language — Python SDK
Target: 256-Core 4D-Torus Neuromorphic Photonic Processor
"""

from .compiler import (
    compile_source,
    compile_c23,
    check_diagnostics,
    find_cron_executable,
    run_esoteric_sim,
    synthesize_esoteric_coprocessor,
    tile_gemm_systolic,
    analyze_optical_budget,
    synthesize_optical_verilog,
    run_comparison_benchmark,
    generate_benchmark_whitepaper,
    cl_audit,
    cl_link,
    chat_eval,
    bpe_encode,
    bpe_decode,
    extract_vision_patches,
    compute_mel_spectrogram,
    run_agent_swarm,
    run_cluster_swarm,
    synthesize_kernel,
    render_swarm_tui,
    get_swarm_tui_telemetry,
    synthesize_mcts_kernel,
    verify_proof_certificate,
    simulate_quantum_bell_state,
    simulate_quantum_qft,
    run_wafer_swarm,
)
from .torch_bridge import (
    CronBitLinear,
    CronRMSNorm,
    CronRingTapeAttention,
    CronTransformerBlock,
    replace_torch_layers,
    pack_ternary_weights,
    find_native_library,
    get_native_version,
    fused_rmsnorm_linear,
    fused_swiglu,
    flash_attention_2,
    export_torch_model,
    from_torch,
)
from .simulator import Simulator
from .photonic import PhotonicBridge
from .kernel import CronKernel, install_kernel_spec
from .clifford import (
    Multivector4D,
    Rotor4D,
    CliffordLinear,
    fold_tensor_4d,
    blade_index,
    blade_sign,
)

__version__ = "1.0.0"
__all__ = [
    "compile_source",
    "compile_c23",
    "check_diagnostics",
    "find_cron_executable",
    "run_esoteric_sim",
    "synthesize_esoteric_coprocessor",
    "tile_gemm_systolic",
    "analyze_optical_budget",
    "synthesize_optical_verilog",
    "run_comparison_benchmark",
    "generate_benchmark_whitepaper",
    "cl_audit",
    "cl_link",
    "chat_eval",
    "bpe_encode",
    "bpe_decode",
    "extract_vision_patches",
    "compute_mel_spectrogram",
    "run_agent_swarm",
    "run_cluster_swarm",
    "synthesize_kernel",
    "render_swarm_tui",
    "get_swarm_tui_telemetry",
    "synthesize_mcts_kernel",
    "verify_proof_certificate",
    "simulate_quantum_bell_state",
    "simulate_quantum_qft",
    "run_wafer_swarm",
    "CronBitLinear",
    "CronRMSNorm",
    "CronRingTapeAttention",
    "CronTransformerBlock",
    "replace_torch_layers",
    "pack_ternary_weights",
    "find_native_library",
    "get_native_version",
    "fused_rmsnorm_linear",
    "fused_swiglu",
    "flash_attention_2",
    "export_torch_model",
    "from_torch",
    "Simulator",
    "PhotonicBridge",
    "CronKernel",
    "install_kernel_spec",
    "Multivector4D",
    "Rotor4D",
    "CliffordLinear",
    "fold_tensor_4d",
]

