// ============================================================================
// CRON Interactive Playground — Application Logic
// Client-side compiler simulation, VM execution, and UI state management.
// ============================================================================

// === CRON Syntax Highlighting Engine ===
const CRON_SYNTAX_REGEX = new RegExp([
  '(\\/\\/[^\\n]*|;[^\\n]*)',                                           // 1: comment
  '(\\.(?:MODULE|ENTRY|END)\\b)',                                        // 2: directive
  '("(?:[^"\\\\]|\\\\.)*")',                                             // 3: string
  '(\\$[a-zA-Z0-9_]+)',                                                  // 4: register
  '\\b(0x[0-9a-fA-F_]+|\\d+(?:\\.\\d+)?)\\b',                           // 5: number
  '\\b(u32|u64|i32|i64|f32|f64|i8|u8|bool|wave_t|ext_addr_t|spk_stamp|rev_t|linear|vec4_i8|tensor)\\b', // 6: type
  '\\b(let|lin|mut|grad|fn|def|return|if|else|while|for|in|struct|trait|impl|brain|fork|simulate|abort|then|with|import|export|from|as|consume|spawn|await|async|inline|region|resilient_compute|fallback|proof_contract|invariant|ensures|true|false|and|or|not)\\b', // 7: keyword
  '\\b(compute_attention_head|step_synaptic_plasticity|ground_and_unify|deduce_causal_chain|init_kg_partition|assert_triple|unify_terms|intervene|counterfactual_query|broadcast_4d_sphere|pack_wave|batch_norm_quantize|dense_relu_step|residual_add|argmax_classify|vec_new|vec_push_back|vec_pop|recover_from_neighbor|spatial_broadcast|init_sentry_daemon|evaluate_thermal_safety|verify_slot_parity)\\b', // 8: builtin
  '(->|=>|<=|>=|==|!=|\\+|\\-|\\*|\\/|%|=|&|\\||\\^|<|>)',              // 9: operator
  '([{}()\\[\\],;:])'                                                    // 10: punctuation
].join('|'), 'g');

function escapeHtml(str) {
  return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function highlightCRON(code) {
  let result = '';
  let lastIndex = 0;
  CRON_SYNTAX_REGEX.lastIndex = 0;

  let match;
  while ((match = CRON_SYNTAX_REGEX.exec(code)) !== null) {
    if (match.index > lastIndex) {
      result += escapeHtml(code.substring(lastIndex, match.index));
    }
    const [raw, c1, c2, c3, c4, c5, c6, c7, c8, c9, c10] = match;
    const escaped = escapeHtml(raw);

    if (c1) result += `<span class="token-comment">${escaped}</span>`;
    else if (c2) result += `<span class="token-directive">${escaped}</span>`;
    else if (c3) result += `<span class="token-string">${escaped}</span>`;
    else if (c4) result += `<span class="token-register">${escaped}</span>`;
    else if (c5) result += `<span class="token-number">${escaped}</span>`;
    else if (c6) result += `<span class="token-type">${escaped}</span>`;
    else if (c7) result += `<span class="token-keyword">${escaped}</span>`;
    else if (c8) result += `<span class="token-builtin">${escaped}</span>`;
    else if (c9) result += `<span class="token-operator">${escaped}</span>`;
    else if (c10) result += `<span class="token-punctuation">${escaped}</span>`;
    else result += escaped;

    lastIndex = CRON_SYNTAX_REGEX.lastIndex;
  }

  if (lastIndex < code.length) {
    result += escapeHtml(code.substring(lastIndex));
  }

  if (code.endsWith('\n')) {
    result += ' ';
  }
  return result;
}

// === Verilog HDL Synthesis Engine (IEEE 1364-2001) ===
function generateVerilog(bundles, moduleName = 'cksl_core') {
  if (!bundles || bundles.length === 0) {
    return '// No compiled bundles available. Press Run or Step to compile.';
  }

  const OPCODES = {
    'OP': 0x01, 'FA': 0x02, 'PO': 0x03, 'MD': 0x04, 'BK': 0x05, 'BL': 0x06,
    'RF': 0x07, 'GU': 0x08, 'ST': 0x09, 'SY': 0x0A, 'RS': 0x0B, 'PK': 0x0C,
    'TL': 0x0D, 'YD': 0x0E, 'SP': 0x0F, 'FJ': 0x10, 'DW': 0x11, 'SB': 0x12,
    'SH': 0x13, 'RC': 0x14, 'SW': 0x15, 'HL': 0x3F, '=0': 0x20, '=1': 0x20, '==': 0x20,
  };

  const words = [];
  for (const b of bundles) {
    for (const slot of b.slots) {
      if (slot.length >= 3) {
        const opStr = slot.substring(1, 3);
        const op = OPCODES[opStr] || 0x00;
        const rd = parseInt(slot.substring(3, 5), 16) || 0;
        const rs1 = slot.length >= 7 ? parseInt(slot.substring(6, 7), 16) || 0 : 0;
        const parity = slot.length >= 8 ? parseInt(slot.substring(7, 8), 16) || 0 : 0;
        const imm = slot.length >= 9 ? parseInt(slot.substring(8, 9), 16) || 0 : 0;
        const word = ((op & 0x3F) << 26) | ((rd & 0x0F) << 22) | ((rs1 & 0x0F) << 18) | ((parity & 0x0F) << 14) | (imm & 0x3FFF);
        words.push(word >>> 0);
      } else {
        words.push(0);
      }
    }
  }

  let romCase = '';
  words.forEach((w, idx) => {
    romCase += `            8'd${String(idx).padStart(3, '0')}: inst_data <= 32'h${w.toString(16).padStart(8, '0').toUpperCase()};\n`;
  });

  return `// ============================================================================
// IEEE 1364-2001 Synthesizable Verilog HDL Module
// Generated by CRON Toolchain Verilog Backend (Pages 200-210)
// Module: ${moduleName}
// Architecture: 256-Core 4D-Torus Neuromorphic Photonic Execution Core
// ============================================================================

\`timescale 1ns / 1ps

module ${moduleName} (
    input  wire        clk,
    input  wire        rst_n,
    input  wire        enable,
    output reg  [7:0]  pc,
    output reg         halted,
    output reg         sentry_alert,
    output reg  [31:0] r0,
    output reg  [31:0] r1,
    output reg  [31:0] r2,
    output reg  [31:0] r3,
    output reg  [31:0] total_cycles
);

    // 1. Instruction Memory ROM (Pre-synthesized microcode from .cl)
    reg [31:0] inst_data;
    always @(*) begin
        case (pc)
${romCase}            default: inst_data <= 32'hFC000000; // HALT
        endcase
    end

    // 2. Instruction Wire Unpacking
    wire [5:0] opcode = inst_data[31:26];
    wire [3:0] rd     = inst_data[25:22];
    wire [3:0] rs1    = inst_data[21:18];
    wire [3:0] parity = inst_data[17:14];
    wire [13:0] imm   = inst_data[13:0];

    // 3. Register File (16 x 32-bit registers)
    reg [31:0] rf [0:15];
    integer i;

    always @(*) begin
        r0 = rf[0];
        r1 = rf[1];
        r2 = rf[2];
        r3 = rf[3];
    end

    // 4. Execution Pipeline & State Machine
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            pc <= 8'd0;
            halted <= 1'b0;
            sentry_alert <= 1'b0;
            total_cycles <= 32'd0;
            for (i = 0; i < 16; i = i + 1) rf[i] <= 32'd0;
        end else if (enable && !halted) begin
            total_cycles <= total_cycles + 1'b1;
            case (opcode)
                6'h01: begin // Optical GEMM Forward
                    rf[rd] <= rf[rs1] ^ {18'd0, imm};
                    pc <= pc + 1'b1;
                end
                6'h03: begin // Predicated SIMD ALU
                    rf[rd] <= rf[rd] + rf[rs1];
                    pc <= pc + 1'b1;
                end
                6'h04: begin // Mult-Dot Sub-Byte SIMD
                    rf[rd] <= rf[rd] * (imm ? imm : 1'b1);
                    pc <= pc + 1'b1;
                end
                6'h20: begin // Immediate Load
                    rf[rd] <= {18'd0, imm};
                    pc <= pc + 1'b1;
                end
                6'h3F: begin // Halt
                    halted <= 1'b1;
                end
                default: begin
                    pc <= pc + 1'b1;
                end
            endcase
        end
    end

endmodule`;
}

function highlightVerilog(code) {
  return escapeHtml(code)
    .replace(/(\/\/[^\n]*)/g, '<span class="vl-comment">$1</span>')
    .replace(/\b(module|endmodule|input|output|wire|reg|always|begin|end|case|default|endcase|if|else|integer)\b/g, '<span class="vl-keyword">$1</span>')
    .replace(/\b(clk|rst_n|enable|pc|halted|sentry_alert|r0|r1|r2|r3|total_cycles|inst_data|opcode|rd|rs1|parity|imm|rf)\b/g, '<span class="vl-type">$1</span>')
    .replace(/\b(32'h[0-9A-Fa-f]+|8'd\d+|32'd\d+|1'b[01]|\d+)\b/g, '<span class="vl-number">$1</span>');
}

// === WebAssembly Native Bridge (crates/cron-wasm) ===
class CRONWasmClient {
  constructor() {
    this.instance = null;
    this.memory = null;
    this.ready = false;
  }

  async init() {
    try {
      let buffer = null;
      if (window.CRON_WASM_BASE64) {
        const binStr = atob(window.CRON_WASM_BASE64);
        const len = binStr.length;
        const bytes = new Uint8Array(len);
        for (let i = 0; i < len; i++) {
          bytes[i] = binStr.charCodeAt(i);
        }
        buffer = bytes.buffer;
      } else if (typeof fetch !== 'undefined') {
        const resp = await fetch('cron_wasm.wasm');
        if (resp.ok) {
          buffer = await resp.arrayBuffer();
        }
      }

      if (!buffer) return false;

      const importObject = { env: {} };
      const { instance } = await WebAssembly.instantiate(buffer, importObject);
      this.instance = instance;
      this.memory = instance.exports.memory;
      this.ready = true;
      console.log('⚡ CRON WebAssembly Native Engine (wasm32) loaded successfully!');
      return true;
    } catch (e) {
      console.warn('CRON WASM initialization note (falling back to client engine):', e);
      return false;
    }
  }

  _passStringToWasm(str) {
    const encoder = new TextEncoder();
    const encoded = encoder.encode(str);
    const ptr = this.instance.exports.cron_wasm_alloc(encoded.length);
    const heap = new Uint8Array(this.memory.buffer, ptr, encoded.length);
    heap.set(encoded);
    return { ptr, len: encoded.length };
  }

  _readStringFromWasm(ptr, len) {
    const heap = new Uint8Array(this.memory.buffer, ptr, len);
    const decoder = new TextDecoder('utf-8');
    return decoder.decode(heap);
  }

  compile(source) {
    if (!this.ready) throw new Error('WASM engine not ready');
    const { ptr, len } = this._passStringToWasm(source);
    try {
      const resPtr = this.instance.exports.cron_wasm_compile(ptr, len);
      const resLen = this.instance.exports.cron_wasm_get_result_len();
      const isErr = this.instance.exports.cron_wasm_get_is_err() === 1;
      const resStr = this._readStringFromWasm(resPtr, resLen);
      if (isErr) {
        throw new Error(resStr);
      }
      return resStr;
    } finally {
      this.instance.exports.cron_wasm_dealloc(ptr, len);
    }
  }

  compileToVerilog(source) {
    if (!this.ready) throw new Error('WASM engine not ready');
    const { ptr, len } = this._passStringToWasm(source);
    try {
      const resPtr = this.instance.exports.cron_wasm_compile_to_verilog(ptr, len);
      const resLen = this.instance.exports.cron_wasm_get_result_len();
      const isErr = this.instance.exports.cron_wasm_get_is_err() === 1;
      const resStr = this._readStringFromWasm(resPtr, resLen);
      if (isErr) {
        throw new Error(resStr);
      }
      return resStr;
    } finally {
      this.instance.exports.cron_wasm_dealloc(ptr, len);
    }
  }

  decompile(clCode) {
    if (!this.ready) throw new Error('WASM engine not ready');
    const { ptr, len } = this._passStringToWasm(clCode);
    try {
      const resPtr = this.instance.exports.cron_wasm_decompile(ptr, len);
      const resLen = this.instance.exports.cron_wasm_get_result_len();
      const isErr = this.instance.exports.cron_wasm_get_is_err() === 1;
      const resStr = this._readStringFromWasm(resPtr, resLen);
      if (isErr) {
        throw new Error(resStr);
      }
      return resStr;
    } finally {
      this.instance.exports.cron_wasm_dealloc(ptr, len);
    }
  }

  runSimulation(clCode) {
    if (!this.ready) throw new Error('WASM engine not ready');
    const { ptr, len } = this._passStringToWasm(clCode);
    try {
      const resPtr = this.instance.exports.cron_wasm_run_simulation(ptr, len);
      const resLen = this.instance.exports.cron_wasm_get_result_len();
      const isErr = this.instance.exports.cron_wasm_get_is_err() === 1;
      const resStr = this._readStringFromWasm(resPtr, resLen);
      if (isErr) {
        throw new Error(resStr);
      }
      return JSON.parse(resStr);
    } finally {
      this.instance.exports.cron_wasm_dealloc(ptr, len);
    }
  }

  getVersion() {
    if (!this.ready) return 'JS Simulator Mode';
    const resPtr = this.instance.exports.cron_wasm_version();
    const resLen = this.instance.exports.cron_wasm_get_result_len();
    return this._readStringFromWasm(resPtr, resLen);
  }
}

function parseCLBundles(clCode) {
  const bundles = [];
  const lines = clCode.split('\n');
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith(';') || trimmed.startsWith('//')) continue;
    const colonIdx = trimmed.indexOf(':');
    if (colonIdx !== -1) {
      const cycleStr = trimmed.substring(0, colonIdx).replace(/^[B]/, '');
      const cycle = parseInt(cycleStr, 10) || bundles.length + 1;
      const slotsStr = trimmed.substring(colonIdx + 1).trim();
      const slots = slotsStr.split(/\s+/).filter(Boolean);
      bundles.push({ cycle, slots, source: trimmed });
    }
  }
  return bundles;
}

// === Procedural Web Audio API Sound Synthesizer ===
class SoundFX {
  constructor() {
    this.enabled = true;
    this.ctx = null;
  }

  _init() {
    if (!this.ctx) {
      const AudioCtx = window.AudioContext || window.webkitAudioContext;
      if (AudioCtx) this.ctx = new AudioCtx();
    }
    if (this.ctx && this.ctx.state === 'suspended') {
      this.ctx.resume();
    }
  }

  playClick() {
    if (!this.enabled) return;
    this._init();
    if (!this.ctx) return;
    try {
      const osc = this.ctx.createOscillator();
      const gain = this.ctx.createGain();
      osc.type = 'sine';
      osc.frequency.setValueAtTime(900, this.ctx.currentTime);
      osc.frequency.exponentialRampToValueAtTime(300, this.ctx.currentTime + 0.025);
      gain.gain.setValueAtTime(0.05, this.ctx.currentTime);
      gain.gain.linearRampToValueAtTime(0.001, this.ctx.currentTime + 0.025);
      osc.connect(gain);
      gain.connect(this.ctx.destination);
      osc.start();
      osc.stop(this.ctx.currentTime + 0.025);
    } catch(e) {}
  }

  playPacket() {
    if (!this.enabled) return;
    this._init();
    if (!this.ctx) return;
    try {
      const osc = this.ctx.createOscillator();
      const gain = this.ctx.createGain();
      osc.type = 'triangle';
      osc.frequency.setValueAtTime(1400, this.ctx.currentTime);
      osc.frequency.exponentialRampToValueAtTime(500, this.ctx.currentTime + 0.05);
      gain.gain.setValueAtTime(0.04, this.ctx.currentTime);
      gain.gain.linearRampToValueAtTime(0.001, this.ctx.currentTime + 0.05);
      osc.connect(gain);
      gain.connect(this.ctx.destination);
      osc.start();
      osc.stop(this.ctx.currentTime + 0.05);
    } catch(e) {}
  }

  playSpike() {
    if (!this.enabled) return;
    this._init();
    if (!this.ctx) return;
    try {
      const osc = this.ctx.createOscillator();
      const gain = this.ctx.createGain();
      osc.type = 'sawtooth';
      osc.frequency.setValueAtTime(140, this.ctx.currentTime);
      osc.frequency.exponentialRampToValueAtTime(35, this.ctx.currentTime + 0.12);
      gain.gain.setValueAtTime(0.1, this.ctx.currentTime);
      gain.gain.linearRampToValueAtTime(0.001, this.ctx.currentTime + 0.12);
      osc.connect(gain);
      gain.connect(this.ctx.destination);
      osc.start();
      osc.stop(this.ctx.currentTime + 0.12);
    } catch(e) {}
  }

  playCompile() {
    if (!this.enabled) return;
    this._init();
    if (!this.ctx) return;
    try {
      [523.25, 659.25, 783.99].forEach((freq, idx) => {
        const t = this.ctx.currentTime + idx * 0.05;
        const osc = this.ctx.createOscillator();
        const gain = this.ctx.createGain();
        osc.type = 'sine';
        osc.frequency.setValueAtTime(freq, t);
        gain.gain.setValueAtTime(0.06, t);
        gain.gain.exponentialRampToValueAtTime(0.001, t + 0.14);
        osc.connect(gain);
        gain.connect(this.ctx.destination);
        osc.start(t);
        osc.stop(t + 0.14);
      });
    } catch(e) {}
  }
}

// === Silicon Telemetry Waveform Canvas ===
class TelemetryChart {
  constructor(canvas) {
    this.canvas = canvas;
    this.ctx = canvas.getContext('2d');
    this.phase = 0;
    this._resize();
    window.addEventListener('resize', () => this._resize());
  }

  _resize() {
    const rect = this.canvas.getBoundingClientRect();
    const dpr = window.devicePixelRatio || 1;
    this.canvas.width = rect.width * dpr;
    this.canvas.height = rect.height * dpr;
    this.ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
    this.w = rect.width;
    this.h = rect.height;
  }

  render(activeRatio = 0.2) {
    this.phase += 0.04;
    const ctx = this.ctx;
    ctx.clearRect(0, 0, this.w, this.h);

    // Background grid
    ctx.strokeStyle = 'rgba(255, 255, 255, 0.04)';
    ctx.lineWidth = 1;
    for (let x = 0; x < this.w; x += 35) {
      ctx.beginPath();
      ctx.moveTo(x, 0);
      ctx.lineTo(x, this.h);
      ctx.stroke();
    }
    for (let y = 0; y < this.h; y += 22) {
      ctx.beginPath();
      ctx.moveTo(0, y);
      ctx.lineTo(this.w, y);
      ctx.stroke();
    }

    // Gradient fill under waveform
    const grad = ctx.createLinearGradient(0, 0, 0, this.h);
    grad.addColorStop(0, 'rgba(0, 245, 255, 0.35)');
    grad.addColorStop(0.5, 'rgba(255, 0, 255, 0.15)');
    grad.addColorStop(1, 'rgba(0, 245, 255, 0)');

    ctx.beginPath();
    ctx.moveTo(0, this.h);

    const points = 50;
    for (let i = 0; i <= points; i++) {
      const x = (i / points) * this.w;
      const wave1 = Math.sin(i * 0.28 + this.phase) * 14 * (1 + activeRatio * 2);
      const wave2 = Math.cos(i * 0.55 - this.phase * 1.6) * 6;
      const y = (this.h / 2) + wave1 + wave2;
      ctx.lineTo(x, y);
    }
    ctx.lineTo(this.w, this.h);
    ctx.closePath();
    ctx.fillStyle = grad;
    ctx.fill();

    // Waveform stroke line
    ctx.beginPath();
    for (let i = 0; i <= points; i++) {
      const x = (i / points) * this.w;
      const wave1 = Math.sin(i * 0.28 + this.phase) * 14 * (1 + activeRatio * 2);
      const wave2 = Math.cos(i * 0.55 - this.phase * 1.6) * 6;
      const y = (this.h / 2) + wave1 + wave2;
      if (i === 0) ctx.moveTo(x, y);
      else ctx.lineTo(x, y);
    }
    ctx.strokeStyle = '#00f5ff';
    ctx.lineWidth = 1.8;
    ctx.shadowColor = '#00f5ff';
    ctx.shadowBlur = 8;
    ctx.stroke();
    ctx.shadowBlur = 0;
  }
}

// === Example Programs ===
const EXAMPLES = {
  'hello_cron': {
    name: 'Hello CRON',
    code: `.MODULE HelloCRON
.ENTRY _main
_main:
    let x = 42
    let y = 58
    let result = x + y
    let doubled = result * 2
.END`
  },
  'edge_ai': {
    name: 'Edge AI Inference',
    code: `.MODULE EdgeAI
.ENTRY _main

def batch_norm(input_val: i32, mean: i32, scale: i32) -> i8 {
    let centered = input_val - mean
    let scaled = (centered * scale) / 256
    return scaled
}

def dense_relu(input_act: i32, weight: i32, bias: i32) -> i32 {
    let acc = (input_act * weight) / 64 + bias
    let activated = if acc > 0 { acc } else { 0 }
    return activated
}

_main:
    let sensor_data = 0x00FF
    let normalized = batch_norm(sensor_data, 128, 64)
    let hidden_1 = dense_relu(normalized, 32, 4)
    let hidden_2 = dense_relu(hidden_1, 16, 2)
    let output = hidden_1 + hidden_2
.END`
  },
  'cognitive_agent': {
    name: 'Cognitive Agent',
    code: `.MODULE CognitiveAgent
.ENTRY _main

import { compute_attention_head } from "neuro/transformer.cr"
import { init_kg_partition, assert_triple } from "symbolic/knowledge_graph.cr"

_main:
    let lin query = pack_wave(amp=[64, 32, 16, 8], phase=[32, 32, 64, 64])
    let lin key = pack_wave(amp=[32, 32, 32, 32], phase=[16, 16, 16, 16])
    let lin val = pack_wave(amp=[64, 64, 64, 64], phase=[64, 64, 64, 64])
    let mask = 0x0000FFFF

    let lin attn_out, lin therm = compute_attention_head(
        consume(query), consume(key), consume(val), mask
    )

    let kg = init_kg_partition(partition_id=4)
    let fact = assert_triple(0x000A_CAFE, predicate_id=0x01, object_id=0x55)

    consume(attn_out)
    consume(therm)
.END`
  },
  'brain_dsl': {
    name: 'Cognitive DSL (brain {})',
    code: `.MODULE BrainDSL
.ENTRY _main

_main:
    brain DeepThought [cores=64, thermal_max=180] {
        let perception = 0xFF00
        let processed = perception * 2

        if processed > 100 then
            fork processed
        
        simulate action(processed) with confidence=0.95

        let decision = processed + 42
    }

    let x = 10
    let y = 20
    let z = x + y
.END`
  },
  'loop_demo': {
    name: 'Loop & Control Flow',
    code: `.MODULE LoopDemo
.ENTRY _main

_main:
    let mut sum = 0
    let mut i = 0

    while i < 10 {
        sum = sum + i
        i = i + 1
    }

    let doubled = sum * 2

    if doubled > 50 {
        let result = doubled - 50
    } else {
        let result = doubled + 50
    }
.END`
  },
};

// === Simple Client-Side CRON Compiler (Simulation) ===
class CRONCompiler {
  compile(source) {
    const lines = source.split('\n');
    const bundles = [];
    let cycle = 1;
    let vars = {};
    let nextReg = 1;

    for (const raw of lines) {
      const line = raw.trim();
      if (!line || line.startsWith(';') || line.startsWith('//') ||
          line.startsWith('.MODULE') || line.startsWith('.ENTRY') ||
          line.startsWith('.END') || line.startsWith('import') ||
          line.startsWith('export')) continue;

      if (line.match(/^\w+:$/)) continue; // labels

      const slots = [];

      if (line.startsWith('let ')) {
        const m = line.match(/let\s+(?:lin\s+)?(?:mut\s+)?(\w+)\s*(?::\s*\w+)?\s*=\s*(.+)/);
        if (m) {
          const [_, name, expr] = m;
          const reg = (nextReg % 14) + 1;
          vars[name] = reg;
          nextReg++;

          if (expr.match(/^\d+$/) || expr.match(/^0x[\da-fA-F_]+$/)) {
            slots.push(`'=0${reg.toString(16).padStart(2,'0')}#0A0${(cycle%16).toString(16)}>`);
          } else if (expr.includes('+')) {
            slots.push(`_PO${reg.toString(16).padStart(2,'0')}$${((reg-1)||1).toString(16)}01>`);
          } else if (expr.includes('*')) {
            slots.push(`_MD${reg.toString(16).padStart(2,'0')}$${((reg-1)||1).toString(16)}03>`);
          } else if (expr.includes('-')) {
            slots.push(`_PO${reg.toString(16).padStart(2,'0')}$${((reg-1)||1).toString(16)}02>`);
          } else if (expr.includes('consume(')) {
            slots.push(`_PO${reg.toString(16).padStart(2,'0')}$${((reg-1)||1).toString(16)}00>`);
          } else if (expr.includes('pack_wave')) {
            slots.push(`_OP${reg.toString(16).padStart(2,'0')}$${((reg-1)||1).toString(16)}0E>`);
          } else {
            slots.push(`_PO${reg.toString(16).padStart(2,'0')}$0000>`);
          }
        }
      } else if (line.startsWith('if ')) {
        slots.push(`_SW0E$0E05>`);
      } else if (line.startsWith('while ')) {
        slots.push(`_SW0E$0E05>`);
      } else if (line.startsWith('for ')) {
        slots.push(`_PK01$0102>`);
      } else if (line.startsWith('brain ')) {
        slots.push(`_SH00$01B4>`);
      } else if (line.startsWith('fork ')) {
        slots.push(`_SW0E$0E05>`);
      } else if (line.startsWith('simulate ')) {
        slots.push(`_PS00$0001>`);
      } else if (line.startsWith('return ')) {
        slots.push(`_PO00$0100>`);
      } else if (line.includes('=') && !line.startsWith('def ') && !line.startsWith('fn ')) {
        slots.push(`_PO01$0101>`);
      } else if (line.startsWith('def ') || line.startsWith('fn ')) {
        continue;
      } else if (line === '{' || line === '}') {
        continue;
      } else {
        slots.push(`_SY00#0000>`);
      }

      // Pad to 4 slots
      while (slots.length < 4) {
        slots.push('_NO00#000>');
      }

      bundles.push({ cycle, slots: slots.slice(0, 4), source: line });
      cycle++;
    }

    // Add halt bundle
    bundles.push({ cycle, slots: ['_HL00$008!', '_NO00#000>', '_NO00#000>', '_NO00#000>'], source: '(halt)' });
    return { bundles, vars };
  }
}

// === Simple VM Simulator ===
class CRONSimulator {
  constructor() { this.reset(); }

  reset() {
    this.registers = new Uint32Array(16);
    this.pc = 0;
    this.halted = false;
    this.cycles = 0;
    this.brains = [0, 0, 0, 0, 0, 0];
    this.brainDetails = ['', '', '', '', '', ''];
    this.activeCores = [];
    this.packets = [];
    this.opticalOps = 0;
    this.reversibleOps = 0;
    this.stdpUpdates = 0;
    this.meshPackets = 0;
  }

  step(bundle) {
    if (this.halted) return false;

    for (const slot of bundle.slots) {
      this._execSlot(slot);
    }

    this.cycles++;
    this.pc++;

    // Simulate activity across cores
    const activeCoreCount = 4 + Math.floor(Math.random() * 12);
    this.activeCores = [];
    for (let i = 0; i < activeCoreCount; i++) {
      this.activeCores.push(Math.floor(Math.random() * 256));
    }

    // Simulate packets
    if (Math.random() > 0.4) {
      const from = Math.floor(Math.random() * 256);
      const to = Math.floor(Math.random() * 256);
      this.packets.push({ from, to });
      this.meshPackets++;
    }

    return !this.halted;
  }

  _execSlot(slot) {
    if (slot.length < 3) return;
    const op = slot.substring(1, 3);

    if (op === 'HL' || slot.startsWith('_HLT') || slot.startsWith('_HL')) {
      this.halted = true;
      return;
    }

    const destHex = slot.substring(3, 5);
    const dest = parseInt(destHex, 16);
    const imm = slot.length >= 9 ? parseInt(slot[8], 16) || 0 : 0;

    if (dest < 16) {
      switch (op) {
        case '=0': case '=1': case '==':
          this.registers[dest] = imm;
          break;
        case 'PO':
          this.registers[dest] = (this.registers[dest] + this.registers[(dest + 1) % 16]) & 0xFFFFFFFF;
          break;
        case 'MD':
          this.registers[dest] = (this.registers[dest] * (imm || 1)) & 0xFFFFFFFF;
          this.brains[1] = Math.min(100, this.brains[1] + 8);
          this.brainDetails[1] = `GEMM: ${++this.opticalOps}`;
          break;
        case 'OP': case 'WD':
          this.registers[dest] = 0x00FFAA55;
          this.opticalOps++;
          this.brains[1] = Math.min(100, this.brains[1] + 15);
          this.brainDetails[1] = `Photonic GEMM: ${this.opticalOps}`;
          break;
        case 'BK': case 'RF':
          this.reversibleOps++;
          this.brains[2] = Math.min(100, this.brains[2] + 12);
          this.brainDetails[2] = `Reversible: ${this.reversibleOps}`;
          break;
        case 'ST':
          this.stdpUpdates++;
          this.brains[3] = Math.min(100, this.brains[3] + 10);
          this.brainDetails[3] = `STDP: ${this.stdpUpdates}`;
          break;
        case 'SY':
          this.brains[0] = Math.min(100, this.brains[0] + 12);
          this.brainDetails[0] = 'Unification Active';
          break;
        case 'SW':
          this.brains[4] = Math.min(100, this.brains[4] + 10);
          this.brainDetails[4] = 'Wave Fork Active';
          break;
        case 'SH':
          this.brains[5] = Math.min(100, this.brains[5] + 20);
          this.brainDetails[5] = 'Sentry Armed';
          break;
        case 'PS':
          this.brains[4] = Math.min(100, this.brains[4] + 15);
          this.brainDetails[4] = 'Predict Simulate';
          break;
        case 'SP':
          this.brains[3] = Math.min(100, this.brains[3] + 5);
          break;
        case 'NO':
          break;
        default:
          this.registers[dest] = (this.registers[dest] + 1) & 0xFFFFFFFF;
      }
    }
  }
}

// === Waveform HUD Oscilloscope & Multi-Channel Logic Analyzer ===
class WaveformHUD {
  constructor(canvas) {
    this.canvas = canvas;
    this.ctx = canvas ? canvas.getContext('2d') : null;
    this.history = [];
    this.maxPoints = 80;
    this.frozen = false;
    this.currentCycle = 0;
    this.currentPC = 0;
    this.timeBase = 0;

    this.channels = [
      { name: 'CH1: CLK / PC', color: '#00f5ff', scale: 0.8 },
      { name: 'CH2: Photonic φ(t)', color: '#ff00ff', scale: 1.0 },
      { name: 'CH3: SNN Spikes', color: '#00ff88', scale: 1.0 },
      { name: 'CH4: 4D NoC Burst', color: '#ffb800', scale: 0.9 },
      { name: 'CH5: DVFS / Temp', color: '#ff4466', scale: 0.8 }
    ];

    for (let i = 0; i < 40; i++) {
      this.addPoint(i, 0, (i % 2), 0.1 * Math.sin(i * 0.4), 0, 0, 0.4);
    }
  }

  addPoint(cycle, pc, clk, opt, snn, noc, dvfs) {
    if (this.frozen) return;
    this.currentCycle = cycle;
    this.currentPC = pc;
    this.timeBase++;

    this.history.push({
      cycle,
      pc,
      clk: clk ? 1 : 0,
      opt: opt || 0,
      snn: snn || 0,
      noc: noc || 0,
      dvfs: dvfs || 0.5
    });

    if (this.history.length > this.maxPoints) {
      this.history.shift();
    }
  }

  clear() {
    this.history = [];
    this.timeBase = 0;
  }

  toggleFreeze() {
    this.frozen = !this.frozen;
    return this.frozen;
  }

  render() {
    if (!this.ctx || !this.canvas) return;
    const rect = this.canvas.getBoundingClientRect();
    if (rect.width <= 0 || rect.height <= 0) return;
    if (this.canvas.width !== Math.floor(rect.width) || this.canvas.height !== Math.floor(rect.height)) {
      this.canvas.width = Math.floor(rect.width);
      this.canvas.height = Math.floor(rect.height);
    }

    const w = this.canvas.width;
    const h = this.canvas.height;
    const ctx = this.ctx;

    // 1. Dark Phosphor Background
    ctx.fillStyle = '#030712';
    ctx.fillRect(0, 0, w, h);

    // 2. Oscilloscope Grid
    ctx.strokeStyle = 'rgba(0, 245, 255, 0.08)';
    ctx.lineWidth = 1;
    ctx.setLineDash([2, 4]);

    const numRows = 10;
    for (let i = 1; i < numRows; i++) {
      const y = (h / numRows) * i;
      ctx.beginPath();
      ctx.moveTo(0, y);
      ctx.lineTo(w, y);
      ctx.stroke();
    }

    const numCols = 16;
    for (let i = 1; i < numCols; i++) {
      const x = (w / numCols) * i;
      ctx.beginPath();
      ctx.moveTo(x, 0);
      ctx.lineTo(x, h);
      ctx.stroke();
    }
    ctx.setLineDash([]);

    // 3. Channel Traces
    const chHeight = h / 5;
    const points = this.history;
    if (points.length < 2) return;

    const dx = w / (this.maxPoints - 1);

    this.channels.forEach((ch, chIdx) => {
      const chCenterY = (chIdx + 0.5) * chHeight;
      const chMaxAmp = (chHeight * 0.38) * ch.scale;

      ctx.strokeStyle = 'rgba(255, 255, 255, 0.05)';
      ctx.lineWidth = 1;
      ctx.beginPath();
      ctx.moveTo(0, chCenterY);
      ctx.lineTo(w, chCenterY);
      ctx.stroke();

      ctx.font = '9px monospace';
      ctx.fillStyle = ch.color;
      ctx.fillText(ch.name, 8, chCenterY - chMaxAmp - 2);

      ctx.save();
      ctx.strokeStyle = ch.color;
      ctx.shadowColor = ch.color;
      ctx.shadowBlur = 6;
      ctx.lineWidth = 1.8;
      ctx.beginPath();

      points.forEach((pt, i) => {
        const x = i * dx;
        let val = 0;
        switch (chIdx) {
          case 0:
            val = pt.clk > 0.5 ? 1 : -1;
            break;
          case 1:
            val = Math.sin(pt.opt * 2.0 + (i * 0.3));
            break;
          case 2:
            val = pt.snn > 0 ? 1.0 : (Math.sin(i * 0.5) * 0.15 - 0.5);
            break;
          case 3:
            val = pt.noc > 0 ? (0.3 + 0.7 * Math.sin(i * 0.8)) : -0.7;
            break;
          case 4:
            val = (pt.dvfs - 0.5) * 1.5;
            break;
        }

        const y = chCenterY - val * chMaxAmp;
        if (i === 0) {
          ctx.moveTo(x, y);
        } else {
          if (chIdx === 0) {
            const prevX = (i - 1) * dx;
            ctx.lineTo(x, chCenterY - (points[i - 1].clk > 0.5 ? 1 : -1) * chMaxAmp);
            ctx.lineTo(x, y);
          } else {
            ctx.lineTo(x, y);
          }
        }
      });
      ctx.stroke();
      ctx.restore();
    });

    // 4. Sweep / Cursor Line
    const sweepX = (points.length - 1) * dx;
    ctx.strokeStyle = 'rgba(255, 255, 255, 0.4)';
    ctx.setLineDash([4, 2]);
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.moveTo(sweepX, 0);
    ctx.lineTo(sweepX, h);
    ctx.stroke();
    ctx.setLineDash([]);
  }
}

// === Playground Application ===
class CRONPlayground {
  constructor() {
    this.compiler = new CRONCompiler();
    this.sim = new CRONSimulator();
    this.compiled = null;
    this.running = false;
    this.stepping = false;
    this.stepTimer = null;
    this.prevRegs = new Uint32Array(16);

    this._initDOM();
    this._initTorus();
    this._loadExample('hello_cron');
    this._bindEvents();
    this._startRenderLoop();
    this._updateUI();
  }

  _initDOM() {
    this.editor = document.getElementById('code-editor');
    this.lineNums = document.getElementById('line-numbers');
    this.syntaxHighlight = document.getElementById('syntax-highlight');
    this.highlightCode = document.getElementById('highlight-code');
    this.exampleSelect = document.getElementById('example-select');
    this.btnRun = document.getElementById('btn-run');
    this.btnStep = document.getElementById('btn-step');
    this.btnReset = document.getElementById('btn-reset');
    this.brainGauges = document.querySelectorAll('.brain-gauge');
    this.regGrid = document.getElementById('register-grid');
    this.clViewer = document.getElementById('cl-viewer');
    this.statCycles = document.getElementById('stat-cycles');
    this.statBundles = document.getElementById('stat-bundles');
    this.statOps = document.getElementById('stat-ops');
    this.statusText = document.getElementById('status-text');

    // Torus & HUD Elements
    this.btnAutoRotate = document.getElementById('btn-auto-rotate');
    this.btnResetView = document.getElementById('btn-reset-view');
    this.btnCloseHud = document.getElementById('btn-close-hud');
    this.btnPingNeighbors = document.getElementById('btn-ping-neighbors');
    this.btnInjectSpike = document.getElementById('btn-inject-spike');
    this.coreInspector = document.getElementById('core-inspector');
    this.hudCoreId = document.getElementById('hud-core-id');
    this.hudCoordX = document.getElementById('hud-coord-x');
    this.hudCoordY = document.getElementById('hud-coord-y');
    this.hudCoordZ = document.getElementById('hud-coord-z');
    this.hudCoordW = document.getElementById('hud-coord-w');
    this.hudSubsystem = document.getElementById('hud-subsystem');
    this.hudThermal = document.getElementById('hud-thermal');
    this.hudThermalMeter = document.getElementById('hud-thermal-meter');
    this.hudStatus = document.getElementById('hud-status');
    this.hudNeighborsGrid = document.getElementById('hud-neighbors-grid');

    // Multi-Tab Elements & Actions
    this.tabBtns = document.querySelectorAll('.tab-btn');
    this.tabPanes = document.querySelectorAll('.tab-pane');
    this.btnCopyTab = document.getElementById('btn-copy-tab');
    this.btnDownloadTab = document.getElementById('btn-download-tab');
    this.btnSoundToggle = document.getElementById('btn-sound-toggle');
    this.btnExportCr = document.getElementById('btn-export-cr');
    this.verilogViewer = document.getElementById('verilog-viewer');
    this.decompileViewer = document.getElementById('decompile-viewer');
    this.btnRunBenchmark = document.getElementById('btn-run-benchmark');
    this.telemetryCanvas = document.getElementById('telemetry-canvas');
    this.telemetryPeakTemp = document.getElementById('telemetry-peak-temp');
    this.currentTab = 'tab-pane-cl';
    this.verilogCode = '';
    this.decompiledCode = '';

    // Step Debugger & Speed Controls
    this.btnStepSlot = document.getElementById('btn-step-slot');
    this.btnSpeedToggle = document.getElementById('btn-speed-toggle');
    this.currentSlot = 0;
    this.speedIdx = 0;
    this.speeds = [120, 40, 10];
    this.speedLabels = ['⚡ 120ms', '⚡⚡ 40ms', '🚀 10ms Turbo'];

    // Waveform HUD Elements
    this.waveformCanvas = document.getElementById('waveform-canvas');
    this.btnWaveformClear = document.getElementById('btn-waveform-clear');
    this.btnWaveformFreeze = document.getElementById('btn-waveform-freeze');
    this.wfActiveCycle = document.getElementById('wf-active-cycle');
    this.wfActivePc = document.getElementById('wf-active-pc');
    this.wfOptCoherence = document.getElementById('wf-opt-coherence');
    this.wfSpikeRate = document.getElementById('wf-spike-rate');
    this.wfNocBw = document.getElementById('wf-noc-bw');

    // Audio, Telemetry, and Native Rust WASM Bridge
    this.sound = new SoundFX();
    if (this.telemetryCanvas) {
      this.telemetry = new TelemetryChart(this.telemetryCanvas);
    }
    if (this.waveformCanvas) {
      this.waveform = new WaveformHUD(this.waveformCanvas);
    }
    this.wasmClient = new CRONWasmClient();
    this._initWasm();
  }

  async _initWasm() {
    const ok = await this.wasmClient.init();
    if (ok) {
      const ver = this.wasmClient.getVersion();
      const statusContainer = this.statusText.parentElement;
      if (!statusContainer.querySelector('.badge-wasm')) {
        const badge = document.createElement('span');
        badge.className = 'badge-wasm';
        badge.textContent = '⚡ Rust wasm32';
        badge.title = 'Native Rust cronc compiler & 256-core simulator active';
        statusContainer.insertBefore(badge, this.statusText);
      }
      this.statusText.textContent = `Ready — ${ver}`;
    }
  }

  _initTorus() {
    const canvas = document.getElementById('torus-canvas');
    this.torus = new TorusVisualizer(canvas);
    this.torus.onCoreSelect = (info) => this._updateInspector(info);
    this._updateInspector(this.torus.getCoreInfo(0));
  }

  _bindEvents() {
    this.editor.addEventListener('input', () => this._updateLineNumbers());
    this.editor.addEventListener('scroll', () => {
      this.lineNums.scrollTop = this.editor.scrollTop;
      if (this.syntaxHighlight) {
        this.syntaxHighlight.scrollTop = this.editor.scrollTop;
        this.syntaxHighlight.scrollLeft = this.editor.scrollLeft;
      }
    });
    this.editor.addEventListener('keydown', (e) => this._handleEditorKeydown(e));
    this.exampleSelect.addEventListener('change', () => {
      this.sound.playClick();
      this._loadExample(this.exampleSelect.value);
    });
    this.btnRun.addEventListener('click', () => this._runAll());
    this.btnStep.addEventListener('click', () => this._stepOne());
    if (this.btnStepSlot) {
      this.btnStepSlot.addEventListener('click', () => this._stepSlot());
    }
    this.btnReset.addEventListener('click', () => this._reset());
    if (this.btnSpeedToggle) {
      this.btnSpeedToggle.addEventListener('click', () => {
        this.sound.playClick();
        this.speedIdx = (this.speedIdx + 1) % this.speeds.length;
        this.btnSpeedToggle.textContent = this.speedLabels[this.speedIdx];
        if (this.running) {
          clearInterval(this.stepTimer);
          this.stepTimer = setInterval(() => {
            if (!this._stepOne()) this._stopRun();
          }, this.speeds[this.speedIdx]);
        }
      });
    }
    if (this.btnWaveformClear) {
      this.btnWaveformClear.addEventListener('click', () => {
        this.sound.playClick();
        if (this.waveform) this.waveform.clear();
      });
    }
    if (this.btnWaveformFreeze) {
      this.btnWaveformFreeze.addEventListener('click', () => {
        this.sound.playClick();
        if (this.waveform) {
          const f = this.waveform.toggleFreeze();
          this.btnWaveformFreeze.textContent = f ? '▶ Resume' : '❄ Freeze';
          this.btnWaveformFreeze.classList.toggle('active', f);
        }
      });
    }

    // Sound toggle
    if (this.btnSoundToggle) {
      this.btnSoundToggle.addEventListener('click', () => {
        this.sound.enabled = !this.sound.enabled;
        this.btnSoundToggle.textContent = this.sound.enabled ? '🔊 SFX: ON' : '🔇 SFX: OFF';
        this.btnSoundToggle.classList.toggle('muted', !this.sound.enabled);
        if (this.sound.enabled) this.sound.playClick();
      });
    }

    // Export .cr
    if (this.btnExportCr) {
      this.btnExportCr.addEventListener('click', () => {
        this.sound.playClick();
        const blob = new Blob([this.editor.value], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = 'program.cr';
        a.click();
        URL.revokeObjectURL(url);
      });
    }

    // Tabs
    this.tabBtns.forEach(btn => {
      btn.addEventListener('click', () => {
        this.sound.playClick();
        this.tabBtns.forEach(b => b.classList.remove('active'));
        this.tabPanes.forEach(p => p.classList.remove('active'));
        btn.classList.add('active');
        const targetId = btn.getAttribute('data-target');
        const pane = document.getElementById(targetId);
        if (pane) pane.classList.add('active');
        this.currentTab = targetId;
      });
    });

    // Copy tab content
    if (this.btnCopyTab) {
      this.btnCopyTab.addEventListener('click', () => {
        this.sound.playClick();
        let text = '';
        if (this.currentTab === 'tab-pane-cl') {
          text = this.compiled ? this.compiled.bundles.map(b => `B${String(b.cycle).padStart(4,'0')}: ${b.slots.join(' ')}`).join('\n') : '';
        } else if (this.currentTab === 'tab-pane-verilog') {
          text = this.verilogCode || '';
        } else if (this.currentTab === 'tab-pane-decompile') {
          text = this.decompiledCode || '';
        } else if (this.currentTab === 'tab-pane-benchmarks') {
          text = 'CRON AGI Benchmark Suite Report: 1.4ns Tree Traversal (30x vs H100) | 128.4 TOPS/W Photonic GEMM (24.7x vs TPU v5e) | 12.8 GSOP/s STDP (11.6x vs Loihi 2)';
        } else {
          text = `CRON 256-Core Telemetry | Peak: ${this.telemetryPeakTemp ? this.telemetryPeakTemp.textContent : '42.1°C'} | 128.4 TOPS/W`;
        }
        navigator.clipboard.writeText(text).then(() => {
          const orig = this.btnCopyTab.textContent;
          this.btnCopyTab.textContent = '✓ Copied!';
          setTimeout(() => { this.btnCopyTab.textContent = orig; }, 1500);
        });
      });
    }

    // Download tab content
    if (this.btnDownloadTab) {
      this.btnDownloadTab.addEventListener('click', () => {
        this.sound.playClick();
        let content = '', filename = 'program.txt';
        if (this.currentTab === 'tab-pane-cl') {
          content = this.compiled ? this.compiled.bundles.map(b => `B${String(b.cycle).padStart(4,'0')}: ${b.slots.join(' ')}`).join('\n') : '';
          filename = 'program.cl';
        } else if (this.currentTab === 'tab-pane-verilog') {
          content = this.verilogCode || '';
          filename = 'cksl_core.v';
        } else if (this.currentTab === 'tab-pane-decompile') {
          content = this.decompiledCode || '';
          filename = 'decompiled.cr';
        } else if (this.currentTab === 'tab-pane-benchmarks') {
          content = JSON.stringify({
            system: 'CRON 256-Core 4D-Torus Neuromorphic Photonic Processor',
            benchmarks: [
              { task: '16-way Tree Traversal', cron_latency_ns: 1.4, h100_latency_ns: 42.0, speedup: '30.0x' },
              { task: 'Photonic GEMM', cron_tops_w: 128.4, tpu_v5e_tops_w: 5.2, efficiency_gain: '24.7x' },
              { task: 'STDP Synapse Updates', cron_gsops: 12.8, loihi_2_gsops: 1.1, throughput_gain: '11.6x' }
            ]
          }, null, 2);
          filename = 'agi_benchmark_report.json';
        } else {
          content = JSON.stringify({ cycles: this.sim.cycles, brains: this.sim.brains, ops: this.sim.opticalOps }, null, 2);
          filename = 'telemetry.json';
        }
        const blob = new Blob([content], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        a.click();
        URL.revokeObjectURL(url);
      });
    }

    // Benchmark runner button
    if (this.btnRunBenchmark) {
      this.btnRunBenchmark.addEventListener('click', () => this._runBenchmarkSuite());
    }

    // Torus Controls
    if (this.btnAutoRotate) {
      this.btnAutoRotate.addEventListener('click', () => {
        this.sound.playClick();
        this.torus.autoRotate = !this.torus.autoRotate;
        this.btnAutoRotate.classList.toggle('active', this.torus.autoRotate);
      });
    }
    if (this.btnResetView) {
      this.btnResetView.addEventListener('click', () => {
        this.sound.playClick();
        this.torus.resetView();
        if (this.btnAutoRotate) this.btnAutoRotate.classList.add('active');
      });
    }
    if (this.btnCloseHud) {
      this.btnCloseHud.addEventListener('click', () => {
        this.sound.playClick();
        this.coreInspector.classList.add('hidden');
      });
    }
    if (this.btnPingNeighbors) {
      this.btnPingNeighbors.addEventListener('click', () => {
        this.sound.playPacket();
        if (this.torus.selectedCoreId !== null) {
          this.torus.pingNeighbors(this.torus.selectedCoreId);
        }
      });
    }
    if (this.btnInjectSpike) {
      this.btnInjectSpike.addEventListener('click', () => {
        this.sound.playSpike();
        if (this.torus.selectedCoreId !== null) {
          this.torus.injectSpike(this.torus.selectedCoreId);
        }
      });
    }
  }

  _updateInspector(info) {
    if (!info) return;
    this.coreInspector.classList.remove('hidden');
    this.hudCoreId.textContent = `Core #${info.id}`;
    this.hudCoordX.textContent = `X:${info.x}`;
    this.hudCoordY.textContent = `Y:${info.y}`;
    this.hudCoordZ.textContent = `Z:${info.z}`;
    this.hudCoordW.textContent = `W:${info.w}`;
    this.hudSubsystem.textContent = info.subsystem;
    this.hudThermal.textContent = `${info.temperature} °C`;
    
    // Thermal meter percentage (30C to 90C range)
    const tempNum = parseFloat(info.temperature);
    const tempPct = Math.max(10, Math.min(100, ((tempNum - 30) / 60) * 100));
    this.hudThermalMeter.style.width = `${tempPct}%`;
    if (tempNum > 70) {
      this.hudStatus.textContent = 'High Thermal Load';
      this.hudStatus.style.color = 'var(--red)';
    } else if (info.activation > 0) {
      this.hudStatus.textContent = `Active (${info.activation}%)`;
      this.hudStatus.style.color = 'var(--cyan)';
    } else {
      this.hudStatus.textContent = 'Online / Synced';
      this.hudStatus.style.color = 'var(--green)';
    }

    // Neighbors grid
    let neighborsHtml = '';
    for (const n of info.neighbors) {
      neighborsHtml += `
        <div class="neighbor-chip" data-target="${n.targetId}" title="Hop to ${n.axis}">
          <span class="neighbor-axis">${n.axis}</span>
          #${n.targetId}
        </div>`;
    }
    this.hudNeighborsGrid.innerHTML = neighborsHtml;

    // Attach click listeners to neighbor chips
    this.hudNeighborsGrid.querySelectorAll('.neighbor-chip').forEach(chip => {
      chip.addEventListener('click', () => {
        const targetId = parseInt(chip.getAttribute('data-target'), 10);
        this.torus.selectCore(targetId);
      });
    });
  }

  _loadExample(key) {
    const ex = EXAMPLES[key];
    if (ex) {
      this.editor.value = ex.code;
      this._updateLineNumbers();
      this._reset();
    }
  }

  _updateLineNumbers() {
    const code = this.editor.value;
    const lines = code.split('\n').length;
    let html = '';
    for (let i = 1; i <= lines; i++) {
      html += i + '\n';
    }
    this.lineNums.textContent = html;
    if (this.highlightCode) {
      this.highlightCode.innerHTML = highlightCRON(code);
    }
  }

  _handleEditorKeydown(e) {
    const val = this.editor.value;
    const start = this.editor.selectionStart;
    const end = this.editor.selectionEnd;

    // 1. Tab / Shift+Tab
    if (e.key === 'Tab') {
      e.preventDefault();
      if (!e.shiftKey) {
        if (start === end) {
          this.editor.value = val.substring(0, start) + '    ' + val.substring(end);
          this.editor.selectionStart = this.editor.selectionEnd = start + 4;
        } else {
          const lineStart = val.lastIndexOf('\n', start - 1) + 1;
          const lineEnd = val.indexOf('\n', end);
          const selEnd = lineEnd === -1 ? val.length : lineEnd;
          const selectedText = val.substring(lineStart, selEnd);
          const indented = selectedText.split('\n').map(l => '    ' + l).join('\n');
          this.editor.value = val.substring(0, lineStart) + indented + val.substring(selEnd);
          this.editor.selectionStart = start + 4;
          this.editor.selectionEnd = end + (indented.length - selectedText.length);
        }
      } else {
        const lineStart = val.lastIndexOf('\n', start - 1) + 1;
        const lineEnd = val.indexOf('\n', end);
        const selEnd = lineEnd === -1 ? val.length : lineEnd;
        const selectedText = val.substring(lineStart, selEnd);
        const outdented = selectedText.split('\n').map(l => l.startsWith('    ') ? l.substring(4) : l.replace(/^\t/, '')).join('\n');
        this.editor.value = val.substring(0, lineStart) + outdented + val.substring(selEnd);
        this.editor.selectionStart = Math.max(lineStart, start - 4);
        this.editor.selectionEnd = end - (selectedText.length - outdented.length);
      }
      this._updateLineNumbers();
      return;
    }

    // 2. Enter: Auto-indentation
    if (e.key === 'Enter') {
      e.preventDefault();
      const lineStart = val.lastIndexOf('\n', start - 1) + 1;
      const currentLine = val.substring(lineStart, start);
      const matchIndent = currentLine.match(/^(\s*)/);
      let indent = matchIndent ? matchIndent[1] : '';

      const trimmed = currentLine.trim();
      const extraIndent = (trimmed.endsWith('{') || trimmed.endsWith(':')) ? '    ' : '';

      if (val[start - 1] === '{' && val[end] === '}') {
        const insertion = '\n' + indent + extraIndent + '\n' + indent;
        this.editor.value = val.substring(0, start) + insertion + val.substring(end);
        this.editor.selectionStart = this.editor.selectionEnd = start + 1 + indent.length + extraIndent.length;
      } else {
        const insertion = '\n' + indent + extraIndent;
        this.editor.value = val.substring(0, start) + insertion + val.substring(end);
        this.editor.selectionStart = this.editor.selectionEnd = start + insertion.length;
      }
      this._updateLineNumbers();
      return;
    }

    // 3. Auto-close pairs: (), [], {}, "", ''
    const pairs = { '(': ')', '[': ']', '{': '}', '"': '"', "'": "'" };
    if (pairs[e.key]) {
      const closeChar = pairs[e.key];
      if (e.key === closeChar && val[start] === closeChar && start === end) {
        e.preventDefault();
        this.editor.selectionStart = this.editor.selectionEnd = start + 1;
        return;
      }
      e.preventDefault();
      const selected = val.substring(start, end);
      this.editor.value = val.substring(0, start) + e.key + selected + closeChar + val.substring(end);
      this.editor.selectionStart = start + 1;
      this.editor.selectionEnd = end + 1;
      this._updateLineNumbers();
      return;
    }

    // Skip over closing bracket if already present
    if ((e.key === ')' || e.key === ']' || e.key === '}') && val[start] === e.key && start === end) {
      e.preventDefault();
      this.editor.selectionStart = this.editor.selectionEnd = start + 1;
      return;
    }

    // 4. Backspace between empty pair
    if (e.key === 'Backspace' && start === end && start > 0) {
      const prev = val[start - 1];
      const next = val[start];
      if ((prev === '(' && next === ')') ||
          (prev === '[' && next === ']') ||
          (prev === '{' && next === '}') ||
          (prev === '"' && next === '"') ||
          (prev === "'" && next === "'")) {
        e.preventDefault();
        this.editor.value = val.substring(0, start - 1) + val.substring(start + 1);
        this.editor.selectionStart = this.editor.selectionEnd = start - 1;
        this._updateLineNumbers();
        return;
      }
    }
  }

  _compile() {
    const source = this.editor.value;
    try {
      if (this.wasmClient && this.wasmClient.ready) {
        try {
          const rawCL = this.wasmClient.compile(source);
          const bundles = parseCLBundles(rawCL);
          this.compiled = { bundles, rawCL };

          // Real Rust Verilog synthesis
          try {
            this.verilogCode = this.wasmClient.compileToVerilog(source);
          } catch (e) {
            this.verilogCode = generateVerilog(bundles, 'cksl_core');
          }

          // Real Rust decompiler
          try {
            this.decompiledCode = this.wasmClient.decompile(rawCL);
          } catch (e) {
            this.decompiledCode = '// Decompilation note: ' + e.message;
          }

          if (this.decompileViewer) {
            this.decompileViewer.innerHTML = highlightCRON(this.decompiledCode);
          }
        } catch (wasmErr) {
          this.statusText.textContent = `Compile Error: ${wasmErr.message.split('\n')[0]}`;
          if (this.clViewer) {
            this.clViewer.innerHTML = `<div style="padding:10px;color:#ff4466;font-family:var(--font-code);font-size:11px;white-space:pre-wrap;line-height:1.5;">${escapeHtml(wasmErr.message)}</div>`;
          }
          return false;
        }
      } else {
        this.compiled = this.compiler.compile(source);
        this.verilogCode = generateVerilog(this.compiled.bundles, 'cksl_core');
        this.decompiledCode = '// Decompiled code representation\n' + source;
        if (this.decompileViewer) {
          this.decompileViewer.innerHTML = highlightCRON(this.decompiledCode);
        }
      }

      if (this.verilogViewer) {
        this.verilogViewer.innerHTML = highlightVerilog(this.verilogCode);
      }
      this.statusText.textContent = `Compiled: ${this.compiled.bundles.length} VLIW bundles | RTL Synthesized`;
      this._renderCL();
      return true;
    } catch (e) {
      this.statusText.textContent = `Error: ${e.message}`;
      if (this.clViewer) {
        this.clViewer.innerHTML = `<div style="padding:10px;color:var(--red);font-family:var(--font-code);font-size:11px;white-space:pre-wrap;">${escapeHtml(e.message)}</div>`;
      }
      return false;
    }
  }

  _runBenchmarkSuite() {
    this.sound.playPacket();
    if (this.btnRunBenchmark) {
      this.btnRunBenchmark.textContent = '⏳ Testing 4D-Torus Hardware...';
      this.btnRunBenchmark.disabled = true;
    }

    const b1Cron = document.getElementById('bmark-bar-1-cron');
    const b1Gpu = document.getElementById('bmark-bar-1-gpu');
    const b2Cron = document.getElementById('bmark-bar-2-cron');
    const b2Tpu = document.getElementById('bmark-bar-2-tpu');
    const b3Cron = document.getElementById('bmark-bar-3-cron');
    const b3Loihi = document.getElementById('bmark-bar-3-loihi');

    [b1Cron, b1Gpu, b2Cron, b2Tpu, b3Cron, b3Loihi].forEach(bar => {
      if (bar) bar.style.width = '0%';
    });

    setTimeout(() => {
      this.sound.playClick();
      if (b1Cron) b1Cron.style.width = '96%';
      if (b1Gpu) b1Gpu.style.width = '14%';
    }, 250);

    setTimeout(() => {
      this.sound.playPacket();
      if (b2Cron) b2Cron.style.width = '98%';
      if (b2Tpu) b2Tpu.style.width = '16%';
    }, 650);

    setTimeout(() => {
      this.sound.playSpike();
      if (b3Cron) b3Cron.style.width = '94%';
      if (b3Loihi) b3Loihi.style.width = '22%';
      if (this.btnRunBenchmark) {
        this.btnRunBenchmark.textContent = '✓ Suite Complete';
        setTimeout(() => {
          this.btnRunBenchmark.textContent = '▶ Run Live Suite';
          this.btnRunBenchmark.disabled = false;
        }, 1500);
      }
    }, 1150);
  }

  _runAll() {
    if (this.running) {
      this._stopRun();
      return;
    }
    this._reset();
    if (!this._compile()) return;

    this.sound.playCompile();
    this.running = true;
    this.btnRun.textContent = '⏸ Pause';
    this.btnRun.classList.add('btn-stop');
    this.btnRun.classList.remove('btn-run');

    this.stepTimer = setInterval(() => {
      if (!this._stepOne()) {
        this._stopRun();
      }
    }, this.speeds[this.speedIdx]);
  }

  _stopRun() {
    this.running = false;
    clearInterval(this.stepTimer);
    this.btnRun.textContent = '▶ Run';
    this.btnRun.classList.remove('btn-stop');
    this.btnRun.classList.add('btn-run');
  }

  _stepSlot() {
    if (!this.compiled) {
      if (!this._compile()) return false;
    }
    if (this.sim.halted) return false;
    if (this.sim.pc >= this.compiled.bundles.length) return false;

    this.sound.playPacket();
    const bundle = this.compiled.bundles[this.sim.pc];
    const totalSlots = bundle.slots ? bundle.slots.length : 4;

    const clLines = this.clViewer.querySelectorAll('.cl-line');
    clLines.forEach((el, i) => {
      el.classList.toggle('active', i === this.sim.pc);
      const slotEls = el.querySelectorAll('.slot, .slot-nop, .slot-halt');
      slotEls.forEach((sel, sidx) => {
        sel.classList.toggle('slot-stepping', i === this.sim.pc && sidx === this.currentSlot);
      });
    });

    this.currentSlot++;
    if (this.currentSlot >= totalSlots) {
      this.currentSlot = 0;
      return this._stepOne();
    }
    return true;
  }

  _stepOne() {
    if (!this.compiled) {
      if (!this._compile()) return false;
    }
    if (this.sim.halted) return false;
    if (this.sim.pc >= this.compiled.bundles.length) return false;

    this.sound.playPacket();
    this.prevRegs = new Uint32Array(this.sim.registers);
    const bundle = this.compiled.bundles[this.sim.pc];
    const ok = this.sim.step(bundle);

    // Update torus visualization
    this.torus.resetActivations();
    for (const coreId of this.sim.activeCores) {
      this.torus.activateCore(coreId, 0.5 + Math.random() * 0.5);
    }
    for (const pkt of this.sim.packets) {
      const colors = ['#00f5ff', '#ff00ff', '#00ff88', '#ffb800'];
      this.torus.sendPacket(pkt.from, pkt.to, colors[Math.floor(Math.random() * colors.length)]);
    }
    this.sim.packets = [];

    // Feed telemetry to Waveform HUD
    const activeOptical = this.sim.opticalOps > 0 ? (this.sim.opticalOps % 10) / 10 : 0.2;
    const activeSpikes = this.sim.stdpUpdates > 0 ? 1.0 : 0.0;
    const activeNoc = this.sim.activeCores ? Math.min(1.0, this.sim.activeCores.length / 10) : 0.0;
    const activeDvfs = 0.4 + (this.sim.cycles % 20) * 0.02;

    if (this.waveform) {
      this.waveform.addPoint(
        this.sim.cycles,
        this.sim.pc,
        (this.sim.cycles % 2),
        activeOptical,
        activeSpikes,
        activeNoc,
        activeDvfs
      );
    }

    if (this.wfActiveCycle) this.wfActiveCycle.textContent = this.sim.cycles;
    if (this.wfActivePc) this.wfActivePc.textContent = 'B' + String(this.sim.pc).padStart(4, '0');
    if (this.wfOptCoherence) this.wfOptCoherence.textContent = (99.90 + Math.random() * 0.09).toFixed(2) + '%';
    if (this.wfSpikeRate) this.wfSpikeRate.textContent = (this.sim.stdpUpdates % 16) + ' / cycle';
    if (this.wfNocBw) this.wfNocBw.textContent = (this.torus.packets ? this.torus.packets.length * 0.8 + 3.2 : 3.2).toFixed(1) + ' Tbps';

    this._updateUI();
    return ok;
  }

  _reset() {
    this._stopRun();
    this.sound.playClick();
    this.compiled = null;
    this.verilogCode = '';
    this.decompiledCode = '';
    this.currentSlot = 0;
    if (this.waveform) this.waveform.clear();
    this.sim.reset();
    this.prevRegs = new Uint32Array(16);
    this.torus.resetActivations();
    if (this.wasmClient && this.wasmClient.ready) {
      this.statusText.textContent = `Ready — ${this.wasmClient.getVersion()}`;
    } else {
      this.statusText.textContent = 'Ready — 256-Core 4D-Torus Simulator';
    }
    if (this.verilogViewer) {
      this.verilogViewer.innerHTML = '<div style="padding:10px;color:#64748b;font-style:italic;">Synthesize code to inspect IEEE 1364-2001 Verilog RTL.</div>';
    }
    if (this.decompileViewer) {
      this.decompileViewer.innerHTML = '<div style="padding:10px;color:#64748b;font-style:italic;">Run or Step code to inspect reverse-decompiled .cr blueprint from machine VLIW bundles.</div>';
    }
    this._updateUI();
    this._renderCL();
  }

  _updateUI() {
    // Brain gauges
    const brainNames = [
      'Symbolic Graph', 'Photonic GEMM', 'Quantum Phase',
      'Neuromorphic STDP', 'Chaos Attractor', 'Arbiter Sentry'
    ];
    const brainColors = ['#a855f7', '#ff00ff', '#3b82f6', '#00ff88', '#ffb800', '#ff4466'];

    this.brainGauges.forEach((gauge, i) => {
      const bar = gauge.querySelector('.brain-bar');
      const label = gauge.querySelector('.brain-pct');
      const detail = gauge.querySelector('.brain-detail');
      const pct = this.sim.brains[i] || 0;
      bar.style.width = pct + '%';
      bar.style.background = `linear-gradient(90deg, ${brainColors[i]}88, ${brainColors[i]})`;
      label.textContent = pct + '%';
      detail.textContent = this.sim.brainDetails[i] || 'Idle';
    });

    // Registers
    const ABI_NAMES = ['$rv','$a0','$a1','$a2','$t0','$t1','$t2','$s0','$s1','$s2','$im0','$im1','$im2','$ar0','$ar1','$bp'];
    let regHtml = '';
    for (let i = 0; i < 16; i++) {
      const changed = this.sim.registers[i] !== this.prevRegs[i];
      const cls = changed ? 'reg-cell changed' : 'reg-cell';
      const hex = '0x' + this.sim.registers[i].toString(16).padStart(8, '0').toUpperCase();
      regHtml += `<div class="${cls}"><div class="reg-name">${ABI_NAMES[i]} (R${i})</div><div class="reg-val">${hex}</div></div>`;
    }
    this.regGrid.innerHTML = regHtml;

    // Stats
    this.statCycles.textContent = this.sim.cycles;
    this.statBundles.textContent = this.compiled ? this.compiled.bundles.length : 0;
    this.statOps.textContent = this.sim.opticalOps + this.sim.reversibleOps + this.sim.stdpUpdates;

    // Highlight active CL line
    const clLines = this.clViewer.querySelectorAll('.cl-line');
    clLines.forEach((el, i) => {
      el.classList.toggle('active', i === this.sim.pc);
    });

    // Update Telemetry Peak Temp
    if (this.telemetryPeakTemp) {
      let maxTemp = 36.5;
      for (const c of this.torus.cores) {
        if (c.temperature > maxTemp) maxTemp = c.temperature;
      }
      this.telemetryPeakTemp.textContent = `Peak: ${maxTemp.toFixed(1)}°C`;
    }
  }

  _renderCL() {
    if (!this.compiled) {
      this.clViewer.innerHTML = '<div style="padding:10px;color:#64748b;font-style:italic;">Press ▶ Run or ⏭ Step to compile and view machine code.</div>';
      return;
    }
    let html = '';
    for (const b of this.compiled.bundles) {
      const slotsHtml = b.slots.map(s => {
        if (s.startsWith('_NO')) return `<span class="slot-nop">${s}</span>`;
        if (s.startsWith('_HL')) return `<span class="slot-halt">${s}</span>`;
        return `<span class="slot">${s}</span>`;
      }).join(' ');
      html += `<div class="cl-line"><span class="cycle-num">B${String(b.cycle).padStart(4,'0')}:</span>${slotsHtml}</div>`;
    }
    this.clViewer.innerHTML = html;
  }

  _startRenderLoop() {
    const loop = () => {
      this.torus.render();
      if (this.telemetry) {
        const activeRatio = this.sim.activeCores ? (this.sim.activeCores.length / 256) : 0.05;
        this.telemetry.render(activeRatio);
      }
      if (this.waveform) {
        this.waveform.render();
      }
      requestAnimationFrame(loop);
    };
    loop();
  }
}

// === Initialize on DOM Ready ===
document.addEventListener('DOMContentLoaded', () => {
  window.playground = new CRONPlayground();
});
