// ============================================================================
// CRON Package Manager: Deterministic Lockfile (cron.lock) & SHA-256 Engine
// Module: cron_cli::pkg::lockfile
// (C) 2026 CRON Language Project - SSS+ Tier Industrial Systems
// ============================================================================

use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LockPackage {
    pub name: String,
    pub version: String,
    pub source: String,
    pub checksum: String, // 64-char SHA-256 hex string
    pub hardware_target: String,
    pub dependencies: Vec<String>,
}

#[derive(Debug, Clone)]
pub struct Lockfile {
    pub lock_version: u32,
    pub packages: BTreeMap<String, LockPackage>,
}

impl Default for Lockfile {
    fn default() -> Self {
        Self {
            lock_version: 1,
            packages: BTreeMap::new(),
        }
    }
}

impl Lockfile {
    pub fn load_from_file<P: AsRef<Path>>(path: P) -> Result<Self, String> {
        let content = fs::read_to_string(path.as_ref())
            .map_err(|e| format!("Failed to read lockfile '{}': {}", path.as_ref().display(), e))?;
        Self::parse(&content)
    }

    pub fn save_to_file<P: AsRef<Path>>(&self, path: P) -> Result<(), String> {
        let content = self.to_lock_string();
        fs::write(path.as_ref(), content)
            .map_err(|e| format!("Failed to write lockfile '{}': {}", path.as_ref().display(), e))
    }

    pub fn parse(content: &str) -> Result<Self, String> {
        let mut lockfile = Self::default();
        let mut current_pkg: Option<LockPackage> = None;

        for line in content.lines() {
            let trimmed = line.trim();
            if trimmed.is_empty() || trimmed.starts_with('#') {
                continue;
            }

            if trimmed == "[[package]]" {
                if let Some(pkg) = current_pkg.take() {
                    lockfile.packages.insert(pkg.name.clone(), pkg);
                }
                current_pkg = Some(LockPackage {
                    name: String::new(),
                    version: String::new(),
                    source: "registry".to_string(),
                    checksum: String::new(),
                    hardware_target: "4d-torus-256-core".to_string(),
                    dependencies: Vec::new(),
                });
                continue;
            }

            if let Some((k, v)) = trimmed.split_once('=') {
                let key = k.trim();
                let val = v.trim().trim_matches('"').trim_matches('\'');

                if let Some(ref mut pkg) = current_pkg {
                    match key {
                        "name" => pkg.name = val.to_string(),
                        "version" => pkg.version = val.to_string(),
                        "source" => pkg.source = val.to_string(),
                        "checksum" => pkg.checksum = val.to_string(),
                        "hardware_target" => pkg.hardware_target = val.to_string(),
                        "dependencies" => {
                            let inner = v.trim().trim_start_matches('[').trim_end_matches(']');
                            pkg.dependencies = inner
                                .split(',')
                                .map(|d| d.trim().trim_matches('"').trim_matches('\'').to_string())
                                .filter(|d| !d.is_empty())
                                .collect();
                        }
                        _ => {}
                    }
                } else if key == "lock_version" {
                    if let Ok(v) = val.parse::<u32>() {
                        lockfile.lock_version = v;
                    }
                }
            }
        }

        if let Some(pkg) = current_pkg.take() {
            lockfile.packages.insert(pkg.name.clone(), pkg);
        }

        Ok(lockfile)
    }

    pub fn to_lock_string(&self) -> String {
        let mut out = String::new();
        out.push_str("# CRON SSS+ Deterministic Silicon Lockfile\n");
        out.push_str("# Automatically generated by `cron`. DO NOT EDIT MANUALLY.\n\n");
        out.push_str(&format!("lock_version = {}\n\n", self.lock_version));

        for pkg in self.packages.values() {
            out.push_str("[[package]]\n");
            out.push_str(&format!("name = \"{}\"\n", pkg.name));
            out.push_str(&format!("version = \"{}\"\n", pkg.version));
            out.push_str(&format!("source = \"{}\"\n", pkg.source));
            out.push_str(&format!("checksum = \"{}\"\n", pkg.checksum));
            out.push_str(&format!("hardware_target = \"{}\"\n", pkg.hardware_target));
            let deps_str = pkg
                .dependencies
                .iter()
                .map(|d| format!("\"{}\"", d))
                .collect::<Vec<_>>()
                .join(", ");
            out.push_str(&format!("dependencies = [{}]\n\n", deps_str));
        }

        out
    }
}

// ----------------------------------------------------------------------------
// Pure-Rust Zero-Dependency SHA-256 Cryptographic Engine
// ----------------------------------------------------------------------------

pub fn sha256_hex(data: &[u8]) -> String {
    let mut h: [u32; 8] = [
        0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a,
        0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19,
    ];

    let k: [u32; 64] = [
        0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5,
        0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
        0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3,
        0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
        0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc,
        0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
        0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7,
        0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
        0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13,
        0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
        0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3,
        0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
        0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5,
        0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
        0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208,
        0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
    ];

    let bit_len = (data.len() as u64) * 8;
    let mut msg = data.to_vec();
    msg.push(0x80);
    while (msg.len() % 64) != 56 {
        msg.push(0x00);
    }
    msg.extend_from_slice(&bit_len.to_be_bytes());

    for chunk in msg.chunks(64) {
        let mut w = [0u32; 64];
        for i in 0..16 {
            w[i] = u32::from_be_bytes(chunk[i * 4..(i + 1) * 4].try_into().unwrap());
        }
        for i in 16..64 {
            let s0 = w[i - 15].rotate_right(7) ^ w[i - 15].rotate_right(18) ^ (w[i - 15] >> 3);
            let s1 = w[i - 2].rotate_right(17) ^ w[i - 2].rotate_right(19) ^ (w[i - 2] >> 10);
            w[i] = w[i - 16].wrapping_add(s0).wrapping_add(w[i - 7]).wrapping_add(s1);
        }

        let mut a = h[0];
        let mut b = h[1];
        let mut c = h[2];
        let mut d = h[3];
        let mut e = h[4];
        let mut f = h[5];
        let mut g = h[6];
        let mut h_var = h[7];

        for i in 0..64 {
            let s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
            let ch = (e & f) ^ ((!e) & g);
            let temp1 = h_var
                .wrapping_add(s1)
                .wrapping_add(ch)
                .wrapping_add(k[i])
                .wrapping_add(w[i]);
            let s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
            let maj = (a & b) ^ (a & c) ^ (b & c);
            let temp2 = s0.wrapping_add(maj);

            h_var = g;
            g = f;
            f = e;
            e = d.wrapping_add(temp1);
            d = c;
            c = b;
            b = a;
            a = temp1.wrapping_add(temp2);
        }

        h[0] = h[0].wrapping_add(a);
        h[1] = h[1].wrapping_add(b);
        h[2] = h[2].wrapping_add(c);
        h[3] = h[3].wrapping_add(d);
        h[4] = h[4].wrapping_add(e);
        h[5] = h[5].wrapping_add(f);
        h[6] = h[6].wrapping_add(g);
        h[7] = h[7].wrapping_add(h_var);
    }

    format!(
        "{:08x}{:08x}{:08x}{:08x}{:08x}{:08x}{:08x}{:08x}",
        h[0], h[1], h[2], h[3], h[4], h[5], h[6], h[7]
    )
}
